=== Instance tracking

Instance tracking is a feature which, when enabled, writes a file on instance startup at the configured location. The file will contain metadata about the instance, such as version, product name, process ID. This file can then later be used by other programs to detect what kind of Hazelcast instances were running on a particular machine by inspecting the file contents. The feature supports both open-source and enterprise members and clients as well as Hazelcast Jet and is disabled by default. Failing to write the file will only generate a warning and the instance is allowed to start.

The file name and the file contents are configurable and may contain placeholders. The placeholders have a prefix to be able to distinguish between a placeholder for the instance tracking feature as opposed to some other placeholder like XML placeholders. We use the same style as the `EncryptionReplacer` by adding a "namespace" to the placeholder prefix. For example, `$HZ_INSTANCE_TRACKING{start_timestamp}` (the namespace here being `HZ_INSTANCE_TRACKING`).

In addition to the above, the hazelcast instance will overwrite any existing file in the configured location. To prevent this, the user can configure the file location using the placeholders in the same way they can be used when defining the file contents. For example, if the file name is configured as `Hazelcast-$HZ_INSTANCE_TRACKING{pid}-$HZ_INSTANCE_TRACKING{start_timestamp}.process`, the file name will contain the process ID and the creation time, making it unique every time the instance is started. The created file is not deleted on node shutdown. As such, it leaves a trace of instances started on a particular machine. The file creation process also is fail-safe meaning that the instance will proceed with starting even though it is unable to write the tracking file and the instance will only log a warning.

[[instance-tracking-configuration]]
==== Configuring instance tracking

Here is an example of programmatic member-side Java configuration:
[source,java]
----
Config config = new Config();
config.getInstanceTrackingConfig()
      .setEnabled(true)
      .setFileName("/tmp/hz-tracking.txt")
      .setFormatPattern("$HZ_INSTANCE_TRACKING{product}:$HZ_INSTANCE_TRACKING{version}");
----

The equivalent XML configuration:
[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.XML
----
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">

    <instance-tracking enabled="true">
        <file-name>/tmp/hz-tracking.txt</file-name>
        <format-pattern>$HZ_INSTANCE_TRACKING{product}:$HZ_INSTANCE_TRACKING{version}</format-pattern>
    </instance-tracking>

</hazelcast>
----

The equivalent YAML configuration:
[source,yml,indent=0,subs="verbatim,attributes",role="secondary"]
.YAML
----
hazelcast:
  instance-tracking:
    enabled: true
    file-name: /tmp/hz-tracking.txt
    format-pattern: $HZ_INSTANCE_TRACKING{product}:$HZ_INSTANCE_TRACKING{version}
----

The user can use this configuration to enable the instance tracking feature, specify the file name and the pattern for the file contents. By default, the feature is disabled, the file name is `Hazelcast.process` in the OS temporary directory as returned by `System.getProperty("java.io.tmpdir")` and the file contents are JSON-formatted key-value pairs of all available metadata.

The client configuration is analogous and only differs in the name of the outer configuration block or config instance containing the instance tracking configuration.

Here is an example when running a client instance:
[source,json]
----
{"product":"Hazelcast", "version":"4.1.7", "pid":27746, "mode":"client", "start_timestamp":1595851430741, "licensed":0}
----

Here is an example when running a member instance in the "server" mode:
[source,json]
----
{"product":"Hazelcast", "version":"4.1.7", "pid":27746, "mode":"server", "start_timestamp":1595851430741, "licensed":1}
----

And here is an example when running a member instance in the "embedded" mode:
[source,json]
----
{"product":"Hazelcast", "version":"4.1.7", "pid":27746, "mode":"embedded", "start_timestamp":1595851430741, "licensed":1}
----

The user can specify a custom format by using a predefined set of available metadata keys. For example:
[source,java]
----
String format = "mode: $HZ_INSTANCE_TRACKING{mode}\n"
        + "product: $HZ_INSTANCE_TRACKING{product}\n"
        + "licensed: $HZ_INSTANCE_TRACKING{licensed}\n"
        + "missing: $HZ_INSTANCE_TRACKING{missing}\n"
        + "broken: $HZ_INSTANCE_TRACKING{broken ";
----

This should produce a file with this content:
[source, plain]
----
mode: embedded
product: Hazelcast
licensed: 0
missing: $HZ_INSTANCE_TRACKING{missing}
broken: $HZ_INSTANCE_TRACKING{broken
----

As can be seen, once we encounter a broken placeholder, all subsequent placeholders are ignored. On the other hand, missing placeholders are skipped and subsequent placeholders are resolved.

The currently valid metadata placeholders and their possible values are:
- `product` - the instance product name, e.g. "Hazelcast" or "Hazelcast Enterprise"
- `version`- the instance version
- `mode` - the instance mode, e.g. "server", "embedded" or "client"
- `start_timestamp` - the timestamp of when the instance was started as the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC.
- `licensed` - If this instance is using a license or not. The value `0` signifies that there is no license set and the value `1` signifies that a license is in use
- `pid` - attempts to get the process ID value. The algorithm does not guarantee to get the process ID on all JVMs and operating systems so please test before use. In case we are unable to get the PID, the value will be `-1`.

The possible values for the `product` placeholder are: `Hazelcast`, `Hazelcast Enterprise`, `Hazelcast Client`, `Hazelcast Client Enterprise`, `Hazelcast Jet`, `Hazelcast Jet Enterprise`.
The possible values for the `mode` placeholder are:
- `server` - this value is used when the instance was started using the `start.sh` or `start.bat` scripts
- `client` - this instance is a Hazelcast client instance
- `embedded` - this instance is embedded in another Java program