=== Management Center

Hazelcast Management Center enables you to monitor and manage your cluster members running Hazelcast.
In addition to monitoring the overall state of your clusters, you can also analyze and browse your
data structures in detail, update map configurations and take thread dumps from members.
You can run scripts (JavaScript, Groovy, etc.) and commands on your members with its scripting and console modules.

See the link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html[Hazelcast Management Center Documentation^]
for its usage details.

==== Toggle Scripting Support

The support for script execution is disabled by default. The reason is security.
Script engines allow to access the underlying system on the members (files and other resources).
Scripts access the system, on which the member runs, with permissions of the running user.

Scripting can be allowed or prevented by specifying the `scripting-enabled` attribute of
the `management-center` element within the Hazelcast member configuration file, as shown below:

[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.XML
----
<hazelcast>
    ...
    <management-center scripting-enabled="false" />
    ...
</hazelcast>
----

[source,yml,indent=0,subs="verbatim,attributes",role="secondary"]
.YAML
----
hazelcast:
  management-center:
    scripting-enabled: false
----

Note that the link:https://jcp.org/en/jsr/detail?id=223[JSR 223^] API is used in Hazelcast IMDG to support scripting.

==== Limiting Source Addresses

It's possible to restrict the source IP addresses from which Management Center operations
are allowed. By default all source connections are allowed.

Defining these source addresses is possible through the `trusted-interfaces`
configuration element. The wildcard (`*`) and ranges can be used.
See the following example:

[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.XML
----
<hazelcast>
    ...
    <management-center>
        <trusted-interfaces>
            <interface>192.168.1.*</interface>
        </trusted-interfaces>
    </management-center>
    ...
</hazelcast>
----

[source,yml,indent=0,subs="verbatim,attributes",role="secondary"]
.YAML
----
hazelcast:
  management-center:
    trusted-interfaces:
      - 192.168.1.*
----

[[clustered-jmx-and-rest]]
==== Clustered JMX and REST via Management Center

[blue]*Hazelcast IMDG Enterprise*

See the link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html[Hazelcast Management Center Documentation^]
for information on Clustered JMX and Clustered REST (via Management Center) features.