
=== JCache Overview

Starting with Hazelcast 3.3.1, Hazelcast offers a specification-compliant JCache implementation. To show our commitment to this
important specification that the Java world was waiting for over a decade, we did not just provide a simple wrapper around our existing
APIs; we implemented a caching structure from the ground up to optimize the behavior to the needs of JCache.
The Hazelcast JCache implementation is 100% TCK (Technology Compatibility Kit) compliant and therefore passes all specification
requirements.

In addition to the given specification, we added some features like asynchronous versions of almost all
operations to give the user extra power.

This chapter gives a basic understanding of how to configure your application and how to setup Hazelcast to be your JCache
provider. It also shows examples of basic JCache usage as well as the additionally offered features that are not part of JSR-107.
To gain a full understanding of the JCache functionality and provided guarantees of different operations, read
the specification document (which is also the main documentation for functionality) at the specification page of https://www.jcp.org/en/jsr/detail?id=107[JSR-107].

==== Supported JCache Versions

Two versions of the JCache specification have been released:

* The original release, version 1.0.0, was released in March 2014. Hazelcast versions 3.3.1 up to 3.9.2 (included) implement version 1.0.0 of the JCache specification. 
* A maintenance release, version 1.1.0 was released in December 2017. Hazelcast version 3.9.3 and higher implement JCache specification version 1.1.0.
 
JCache 1.1.0 is backwards compatible with JCache 1.0.0. As a maintenance release, it introduces clarifications and bug fixes in the specification, reference implementation
and TCK, without introducing any additional features. 
 
==== Upgrading from JCache 1.0.0 to 1.1.0
 
When upgrading from a Hazelcast version which implements JCache 1.0.0 to a version that implements version 1.1.0 of the specification, some behavioral differences must be taken into account:

* Invoking `CacheManager.getCacheNames` on a closed `CacheManager` will return an empty iterator under JCache 1.0.0, while under JCache 1.1.0 will throw an `IllegalStateException`.
* Runtime type checking is removed from `CacheManager.getCache(String)`, so when using JCache 1.1.0 one may obtain a `Cache` by name even when its configured key/value types are not known.
* Statistics effects of `Cache.putIfAbsent` on misses and hits are properly applied when using JCache 1.1.0, while under JCache 1.0.0 misses and hits were not updated.
 
Note that these behavioral differences apply on the Hazelcast member that executes the operation. Thus when performing a rolling member upgrade from a JCache 1.0.0-compliant Hazelcast version to a newer Hazelcast version that supports JCache 1.1.0, operations executed on the new members will exhibit JCache 1.1.0 behavior while those executed on old members will implement JCache 1.0.0 behavior.  

The complete list of issues addressed in JCache specification version 1.1.0 is https://github.com/jsr107/jsr107spec/milestone/2?closed=1"[available on Github].
