
[[distributed-events]]
== Distributed Events

You can register for Hazelcast entry events so you will be notified when those events occur. Event Listeners are cluster-wide--when a listener is registered in one member of cluster, it is actually registered for events that originated at any member in the cluster. When a new member joins, events originated at the new member will also be delivered.

An Event is created only if you registered an event listener. If no listener is registered, then no event will be created. If you provided a predicate when you registered the event listener, pass the predicate before sending the event to the listener (member/client).

As a rule of thumb, your event listener should not implement heavy processes in its event methods that block the thread for a long time. If needed, you can use `ExecutorService` to transfer long running processes to another thread and thus offload the current listener thread.

NOTE: In a failover scenario, events are not highly available and may get lost. Eventing mechanism is being improved for failover scenarios.


Hazelcast offers the following event listeners. 

For cluster events:

* **Membership Listener** for cluster membership events.
* **Distributed Object Listener** for distributed object creation and destroy events.
* **Migration Listener** for partition migration start and complete events.
* **Partition Lost Listener** for partition lost events.
* **Lifecycle Listener** for `HazelcastInstance` lifecycle events.
* **Client Listener** for client connection events.


For distributed object events:

* **Entry Listener** for `IMap` and `MultiMap` entry events.
* **Item Listener** for `IQueue`, `ISet` and `IList` item events.
* **Message Listener** for `ITopic` message events.

For Hazelcast JCache implementation:

* **Cache Entry Listener**, please see <<cacheentrylistener, CacheEntryListener>>.
* **Cache Partition Lost Listener**, please see <<icache-partition-lost-listener, ICache Partition Lost Listener>>.

For Hazelcast clients:

* **Lifecycle Listener**
* **Membership Listener**
* **Distributed Object Listener**

[[cluster-events]]
=== Cluster Events

[[listening-for-member-events]]
==== Listening for Member Events

The Membership Listener interface has methods that are invoked for the following events.

* `memberAdded`: A new member is added to the cluster.
* `memberRemoved`: An existing member leaves the cluster.
* `memberAttributeChanged`: An attribute of a member is changed. Please refer to <<defining-member-attributes, Defining Member Attributes>> to learn about member attributes.

To write a Membership Listener class, you implement the MembershipListener interface and its methods.

The following is an example Membership Listener class.

[source,java]
----
public class ClusterMembershipListener implements MembershipListener {

    public void memberAdded(MembershipEvent membershipEvent) {
        System.err.println("Added: " + membershipEvent);
    }

    public void memberRemoved(MembershipEvent membershipEvent) {
        System.err.println("Removed: " + membershipEvent);
    }

    public void memberAttributeChanged(MemberAttributeEvent memberAttributeEvent) {
        System.err.println("Member attribute changed: " + memberAttributeEvent);
    }
}
----

When a respective event is fired, the membership listener outputs the addresses of the members that joined and left, and also which attribute changed on which member.

[[registering-membership-listeners]]
===== Registering Membership Listeners

After you create your class, you can configure your cluster to include the membership listener. Below is an example using the method `addMembershipListener`.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getCluster().addMembershipListener( new ClusterMembershipListener() );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
Config config = new Config();
config.addListenerConfig(
new ListenerConfig( "com.yourpackage.ClusterMembershipListener" ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <listeners>
      <listener>
         com.yourpackage.ClusterMembershipListener
      </listener>
   </listeners>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:listeners>
 <hz:listener class-name="com.yourpackage.ClusterMembershipListener"/>
 <hz:listener implementation="MembershipListener"/>
</hz:listeners>
```

[[listening-for-distributed-object-events]]
==== Listening for Distributed Object Events

The Distributed Object Listener methods `distributedObjectCreated` and `distributedObjectDestroyed` are invoked when a distributed object is created and destroyed throughout the cluster. To write a Distributed Object Listener class, you implement the DistributedObjectListener interface and its methods.

The following is an example Distributed Object Listener class.

[source,java]
----
include::{javasource}/distributedevents/SampleDistObjListener.java[tag=distobjlistener]
----


When a respective event is fired, the distributed object listener outputs the event type, the object name and a service name (for example, for a Map object the service name is `"hz:impl:mapService"`).

[[registering-distributed-object-listeners]]
===== Registering Distributed Object Listeners

After you create your class, you can configure your cluster to include distributed object listeners. Below is an example using the method `addDistributedObjectListener`. You can also see this portion in the above class creation.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
SampleDistObjListener sample = new SampleDistObjListener();

hazelcastInstance.addDistributedObjectListener( sample );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register the listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
config.addListenerConfig(
new ListenerConfig( "com.yourpackage.SampleDistObjListener" ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <listeners>
      <listener>
         com.yourpackage.SampleDistObjListener
      </listener>
   </listeners>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:listeners>
   <hz:listener class-name="com.yourpackage.SampleDistObjListener"/>
   <hz:listener implementation="DistributedObjectListener"/>
</hz:listeners>
```

[[listening-for-migration-events]]
==== Listening for Migration Events

The Migration Listener interface has methods that are invoked for the following events:

* `migrationStarted`: A partition migration is started.
* `migrationCompleted`: A partition migration is completed.
* `migrationFailed`: A partition migration failed.

To write a Migration Listener class, you implement the MigrationListener interface and its methods.

The following is an example Migration Listener class.

[source,java]
----
include::{javasource}/distributedevents/ClusterMigrationListener.java[tag=clstrmigrationlistener]
----


When a respective event is fired, the migration listener outputs the partition ID, status of the migration, the old member and the new member. The following is an example output.

```
Started: MigrationEvent{partitionId=98, oldOwner=Member [127.0.0.1]:5701,
newOwner=Member [127.0.0.1]:5702 this} 
```

===== Registering Migration Listeners

After you create your class, you can configure your cluster to include migration listeners. Below is an example using the method `addMigrationListener`.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

PartitionService partitionService = hazelcastInstance.getPartitionService();
partitionService.addMigrationListener( new ClusterMigrationListener() );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register the listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
config.addListenerConfig( 
new ListenerConfig( "com.yourpackage.ClusterMigrationListener" ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <listeners>
      <listener>
         com.yourpackage.ClusterMigrationListener
      </listener>
   </listeners>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:listeners>
   <hz:listener class-name="com.yourpackage.ClusterMigrationListener"/>
   <hz:listener implementation="MigrationListener"/>
</hz:listeners>
```

[[listening-for-partition-lost-events]]
==== Listening for Partition Lost Events

Hazelcast provides fault-tolerance by keeping multiple copies of your data. For each partition, one of your cluster members becomes the owner and some of the other members become replica members, based on your configuration. Nevertheless, data loss may occur if a few members crash simultaneously.

Let`s consider the following example with three members: N1, N2, N3 for a given partition-0. N1 is owner of partition-0, and N2 and N3 are the first and second replicas respectively. If N1 and N2 crash simultaneously, partition-0 loses its data that is configured with less than two backups.
For instance, if we configure a map with one backup, that map loses its data in partition-0 since both owner and first replica of partition-0 have crashed. However, if we configure our map with two backups, it does not lose any data since a copy of partition-0's data for the given map
also resides in N3. 

The Partition Lost Listener notifies for possible data loss occurrences with the information of how many replicas are lost for a partition. It listens to `PartitionLostEvent` instances. Partition lost events are dispatched per partition. 

Partition loss detection is done after a member crash is detected by the other members and the crashed member is removed from the cluster. Please note that false-positive `PartitionLostEvent` instances may be fired on the network split errors. 

===== Writing a Partition Lost Listener Class

To write a Partition Lost Listener, you implement the PartitionLostListener interface and its `partitionLost` method, which is invoked when a partition loses its owner and all backups.

The following is an example Partition Lost Listener class. 

[source,java]
----
public class ConsoleLoggingPartitionLostListener implements PartitionLostListener {
    @Override
    public void partitionLost(PartitionLostEvent event) {
        System.out.println(event);
    }
} 
----

When a `PartitionLostEvent` is fired, the partition lost listener given above outputs the partition ID, the replica index that is lost, and the member that has detected the partition loss. The following is an example output.

```
com.hazelcast.partition.PartitionLostEvent{partitionId=242, lostBackupCount=0, 
eventSource=Address[192.168.2.49]:5701}
```

===== Registering Partition Lost Listeners

After you create your class, you can configure your cluster programmatically or declaratively to include the partition lost listener. Below is an example of its programmatic configuration.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getPartitionService().addPartitionLostListener( new ConsoleLoggingPartitionLostListener() );
```

The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <listeners>
      <listener>
         com.yourpackage.ConsoleLoggingPartitionLostListener
      </listener>
   </listeners>
   ...
</hazelcast>
```


[[listening-for-lifecycle-events]]
==== Listening for Lifecycle Events

The Lifecycle Listener notifies for the following events:

* `STARTING`: A member is starting.
* `STARTED`: A member started.
* `SHUTTING_DOWN`: A member is shutting down.
* `SHUTDOWN`: A member's shutdown has completed.
* `MERGING`: A member is merging with the cluster.
* `MERGED`: A member's merge operation has completed.
* `CLIENT_CONNECTED`: A Hazelcast Client connected to the cluster.
* `CLIENT_DISCONNECTED`: A Hazelcast Client disconnected from the cluster.

The following is an example Lifecycle Listener class.

[source,java]
----
public class NodeLifecycleListener implements LifecycleListener {
     @Override
     public void stateChanged(LifecycleEvent event) {
         System.err.println(event);
     }
}
----

This listener is local to an individual member. It notifies the application that uses Hazelcast about the events mentioned above for a particular member. 

===== Registering Lifecycle Listeners

After you create your class, you can configure your cluster to include lifecycle listeners. Below is an example using the method `addLifecycleListener`.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
hazelcastInstance.getLifecycleService().addLifecycleListener( new NodeLifecycleListener() );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register the listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
config.addListenerConfig(
    new ListenerConfig( "com.yourpackage.NodeLifecycleListener" ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <listeners>
      <listener>
         com.yourpackage.NodeLifecycleListener
      </listener>
   </listeners>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:listeners>
   <hz:listener class-name="com.yourpackage.NodeLifecycleListener"/>
   <hz:listener implementation="LifecycleListener"/>
</hz:listeners>
```

[[listening-for-clients]]
==== Listening for Clients

The Client Listener is used by the Hazelcast cluster members. It notifies the cluster members when a client is connected to or disconnected from the cluster.

To write a client listener class, you implement the `ClientListener` interface and its methods `clientConnected` and `clientDisconnected`,
which are invoked when a client is connected to or disconnected from the cluster. You can add your client listener as shown below.

```
hazelcastInstance.getClientService().addClientListener(new SampleClientListener());
```

The following is the equivalent declarative configuration.

```
<listeners>
   <listener>
      com.yourpackage.SampleClientListener
   </listener>
</listeners>
```

The following is the equivalent configuration in the Spring context.

```
<hz:listeners>
   <hz:listener class-name="com.yourpackage.SampleClientListener"/>
   <hz:listener implementation="com.yourpackage.SampleClientListener"/>
</hz:listeners>
```

NOTE: You can also add event listeners to a Hazelcast client. Please refer to <<configuring-client-listeners, Client Listenerconfig>> for the related information.

[[distributed-object-events]]
=== Distributed Object Events

==== Listening for Map Events

You can listen to map-wide or entry-based events using the listeners provided by the Hazelcast's eventing framework. To listen to these events, implement a `MapListener` sub-interface.

A map-wide event is fired as a result of a map-wide operation. For 
example, `IMap.clear()` or `IMap.evictAll()`.
An entry-based event is fired after the operations that affect a 
specific entry. For example, `IMap.remove()` or `IMap.evict()`.

===== Catching a Map Event

To catch an event, you should explicitly 
implement a corresponding sub-interface of a `MapListener`, 
such as `EntryAddedListener` or `MapClearedListener`. 

NOTE: The `EntryListener` interface still can be implemented (we kept
it for backward compatibility reasons). However, if you need to listen to a 
different event, one that is not available in the `EntryListener` interface, you should also 
implement a relevant `MapListener` sub-interface.*

Let's take a look at the following class example.

[source,java]
----
include::{javasource}/distributedevents/Listen.java[tag=listen]
----


Now, let's perform some modifications on the map entries using the following example code.

[source,java]
----
include::{javasource}/distributedevents/ModifyMap.java[tag=modify]
----


If you execute the `Listen` class and then the `Modify` class, you get the following output 
produced by the `Listen` class. 

```
Entry Added:EntryEvent{entryEventType=ADDED, member=Member [192.168.1.100]]:5702
 - ffedb655-bbad-43ea-aee8-d429d37ce528, name='somemap', key=11455268066242,
 oldValue=null, value=1, mergingValue=null}

Entry Updated:EntryEvent{entryEventType=UPDATED, member=Member [192.168.1.100]]:5702
 - ffedb655-bbad-43ea-aee8-d429d37ce528, name='somemap', key=11455268066242,
 oldValue=1, value=2, mergingValue=null}

Entry Removed:EntryEvent{entryEventType=REMOVED, member=Member [192.168.1.100]]:5702
 - ffedb655-bbad-43ea-aee8-d429d37ce528, name='somemap', key=11455268066242,
 oldValue=null, value=null, mergingValue=null}
```

NOTE: Please note that the method `IMap.clear()` does not fire an "EntryRemoved" event, but fires a "MapCleared" event.

NOTE: Listeners have to offload all blocking operations to another thread (pool).


==== Listening for Lost Map Partitions

You can listen to `MapPartitionLostEvent` instances by registering an implementation 
of `MapPartitionLostListener`, which is also a sub-interface of `MapListener`.

Let`s consider the following example code:

[source,java]
----
include::{javasource}/distributedevents/ListenMapPartitionLostEvents.java[tag=lmple]
----


Within this example code, a `MapPartitionLostListener` implementation is registered to a map 
that is configured with one backup. For this particular map and any of the partitions in the 
system, if the partition owner member and its first backup member crash simultaneously, the 
given `MapPartitionLostListener` receives a 
corresponding `MapPartitionLostEvent`. If only a single member crashes in the cluster, 
there will be no `MapPartitionLostEvent` fired for this map since backups for the partitions 
owned by the crashed member are kept on other members. 

Please refer to <<listening-for-partition-lost-events, Listening for Partition Lost Events>> for more 
information about partition lost detection and partition lost events.

===== Registering Map Listeners

After you create your listener class, you can configure your cluster to include map listeners using the method `addEntryListener` (as you can see in the example `Listen` class above). Below is the related portion from this code, showing how to register a map listener.

```
HazelcastInstance hz = Hazelcast.newHazelcastInstance();
IMap<String, String> map = hz.getMap( "somemap" );
map.addEntryListener( new MyEntryListener(), true );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register listeners in configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
mapConfig.addEntryListenerConfig(
new EntryListenerConfig( "com.yourpackage.MyEntryListener", 
                                 false, false ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <map name="somemap">
      ...
      <entry-listeners>
         <entry-listener include-value="false" local="false">
            com.yourpackage.MyEntryListener
         </entry-listener>
      </entry-listeners>
   </map>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:map name="somemap">
   <hz:entry-listeners>
      <hz:entry-listener include-value="true"
         class-name="com.hazelcast.spring.DummyEntryListener"/>
      <hz:entry-listener implementation="dummyEntryListener" local="true"/>
   </hz:entry-listeners>
</hz:map>
```

===== Map Listener Attributes

As you see, there are attributes of the map listeners in the above examples: `include-value` and `local`. The attribute `include-value` is a boolean attribute that is optional, and if you set it to `true`, the map event will contain the map value. Its default value is `true`.

The attribute `local` is also a boolean attribute that is optional, and if you set it to `true`, you can listen to the map on the local member. Its default value is `false`.


==== Listening for MultiMap Events

You can listen to entry-based events in the MultiMap using `EntryListener`. The following is an example entry listener implementation for MultiMap.

[source,java]
----
include::{javasource}/distributedevents/SampleEntryListener.java[tag=sel]
----


===== Registering MultiMap Listeners

After you create your listener class, you can configure your cluster to include MultiMap listeners using the method `addEntryListener`. Below is the related portion from a code, showing how to register a map listener.

```
HazelcastInstance hz = Hazelcast.newHazelcastInstance();
MultiMap<String, String> map = hz.getMultiMap( "somemap" );
map.addEntryListener( new SampleEntryListener(), true );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
multiMapConfig.addEntryListenerConfig(
  new EntryListenerConfig( "com.yourpackage.SampleEntryListener",
    false, false ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <multimap name="somemap">
      <value-collection-type>SET</value-collection-type>
      <entry-listeners>
         <entry-listener include-value="false" local="false">
            com.yourpackage.SampleEntryListener
         </entry-listener>
      </entry-listeners>
   </multimap>
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:multimap name="somemap" value-collection-type="SET">
   <hz:entry-listeners>
      <hz:entry-listener include-value="false"
         class-name="com.yourpackage.SampleEntryListener"/>
      <hz:entry-listener implementation="EntryListener" local="false"/>
   </hz:entry-listeners>
</hz:multimap>
```

===== MultiMap Listener Attributes

As you see, there are attributes of the MultiMap listeners in the above examples: `include-value` and `local`. The attribute `include-value` is a boolean attribute that is optional, and if you set it to `true`, the MultiMap event will contain the map value. Its default value is `true`.

The attribute `local` is also a boolean attribute that is optional, and if you set it to `true`, you can listen to the MultiMap on the local member. Its default value is `false`.


==== Listening for Item Events

The Item Listener is used by the Hazelcast `IQueue`, `ISet` and `IList` interfaces.

To write an Item Listener class, you implement the ItemListener interface and its methods `itemAdded` and `itemRemoved`. These methods
are invoked when an item is added or removed.

The following is an example Item Listener class for an `ISet` structure.

[source,java]
----
public class SampleItemListener implements ItemListener<Price> {

    @Override
    public void itemAdded(ItemEvent<Price> event) {
        System.out.println( "Item added:  " + event );
    }

    @Override
    public void itemRemoved(ItemEvent<Price> event) {
        System.out.println( "Item removed: " + event );
    }
}
----

NOTE: You can use `ICollection` when creating any of the collection (queue, set and list) data structures, as shown above. You can also use `IQueue`, `ISet` or `IList` instead of `ICollection`.

===== Registering Item Listeners

After you create your class, you can configure your cluster to include item listeners. Below is an example using the method `addItemListener` for `ISet` (it applies also to `IQueue` and `IList`). You can also see this portion in the above class creation.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

ICollection<Price> set = hazelcastInstance.getSet( "default" );
// or ISet<Prices> set = hazelcastInstance.getSet( "default" );
set.addItemListener( new SampleItemListener(), true );
```

With the above approach, there is the possibility of missing events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register listeners in the configuration. You can register listeners using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
setConfig.addItemListenerConfig(
new ItemListenerConfig( "com.yourpackage.SampleItemListener", true ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
  <set>
    <item-listeners>
      <item-listener include-value="true">
        com.yourpackage.SampleItemListener
      </item-listener>
    </item-listeners>
  </set>
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:set name="default" >
  <hz:item-listeners>
    <hz:item-listener include-value="true"
      class-name="com.yourpackage.SampleItemListener"/>
  </hz:item-listeners>
</hz:set>
```

===== Item Listener Attributes

As you see, there is an attribute in the above examples: `include-value`. It is a boolean attribute that is optional, and if you set it to `true`, the item event will contain the item value. Its default value is `true`.

There is also another attribute called `local`, which is not shown in the above examples. It is also a boolean attribute that is optional, and if you set it to `true`, you can listen to the items on the local member. Its default value is `false`.


==== Listening for Topic Messages

The Message Listener is used by the `ITopic` interface. It notifies when a message is received for the registered topic.

To write a Message Listener class, you implement the MessageListener interface and its method `onMessage`, which is invoked
when a message is received for the registered topic.

The following is an example Message Listener class.

[source,java]
----
public class SampleMessageListener implements MessageListener<MyEvent> {

    public void onMessage( Message<MyEvent> message ) {
        MyEvent myEvent = message.getMessageObject();
        System.out.println( "Message received = " + myEvent.toString() );
    }
}
----

===== Registering Message Listeners

After you create your class, you can configure your cluster to include message listeners. Below is an example using the method `addMessageListener`.

```
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

ITopic topic = hazelcastInstance.getTopic( "default" );
topic.addMessageListener( new SampleMessageListener() );
```

With the above approach, there is the possibility of missing messaging events between the creation of the instance and registering the listener. To overcome this race condition, Hazelcast allows you to register this listener in the configuration. You can register it using declarative, programmatic, or Spring configuration, as shown below.

The following is an example programmatic configuration.

```
topicConfig.addMessageListenerConfig(
  new ListenerConfig( "com.yourpackage.SampleMessageListener" ) );
```


The following is an example of the equivalent declarative configuration. 

```
<hazelcast>
   ...
   <topic name="default">
      <message-listeners>
         <message-listener>
            com.yourpackage.SampleMessageListener
         </message-listener>
      </message-listeners>
   </topic>   
   ...
</hazelcast>
```

The following is an example of the equivalent Spring configuration.

```
<hz:topic name="default">
  <hz:message-listeners>
    <hz:message-listener 
      class-name="com.yourpackage.SampleMessageListener"/>
  </hz:message-listeners>
</hz:topic>
```

=== Event Listeners for Hazelcast Clients

You can add event listeners to a Hazelcast Java client. You can configure the following listeners to listen to the events on the client side. Please see the respective sections under the <<cluster-events, Cluster Events section>> for example codes.

- <<listening-for-lifecycle-events, Lifecycle Listener>>: Notifies when the client is starting, started, shutting down, and shutdown.
- <<listening-for-member-events, Membership Listener>>: Notifies when a member joins to/leaves the cluster to which the client is connected, or when an attribute is changed in a member.
- <<listening-for-distributed-object-events, DistributedObject Listener>>: Notifies when a distributed object is created or destroyed throughout the cluster to which the client is connected.

NOTE: Please refer to the <<configuring-client-listeners, Configuring Client Listeners section>> for more information.

=== Global Event Configuration

* `hazelcast.event.queue.capacity`: default value is 1000000
* `hazelcast.event.queue.timeout.millis`: default value is 250
* `hazelcast.event.thread.count`: default value is 5

A striped executor in each cluster member controls and dispatches the received events. This striped executor also guarantees the event order. For all events in Hazelcast, the order in which events are generated and the order in which they are published are guaranteed for given keys. For map and multimap, the order is preserved for the operations on the same key of the entry. For list, set, topic and queue, the order is preserved for events on that instance of the distributed data structure.

To achieve the order guarantee, you make only one thread responsible for a particular set of events (entry events of a key in a map, item events of a collection, etc.) in `StripedExecutor` (within `com.hazelcast.util.executor`).

If the event queue reaches its capacity (`hazelcast.event.queue.capacity`) and the last item cannot be put into the event queue for the period specified in `hazelcast.event.queue.timeout.millis`, these events will be dropped with a warning message, such as "EventQueue overloaded".

If event listeners perform a computation that takes a long time, the event queue can reach its maximum capacity and lose events. For map and multimap, you can configure `hazelcast.event.thread.count` to a higher value so that fewer collisions occur for keys, and therefore worker threads will not block each other in `StripedExecutor`. For list, set, topic and queue, you should offload heavy work to another thread. To preserve order guarantee, you should implement similar logic with `StripedExecutor` in the offloaded thread pool.









