== SQL

The SQL service provided by Hazelcast allows you to query data stored in `IMap` declaratively.

WARNING: The SQL feature is currently in beta. The compatibility between versions
is not guaranteed. API might change between versions without notice.

=== Example: How to Query an IMap using SQL

Consider that we have a map called `emp` that contains values of type `Employee`:

[source,java]
----
public class Employee implements Serializable {
    private String name;
    private int age;

    public Employee(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }
}
----

The following code prints names of the employees whose age is less than 30:

[source,java]
----
try (SqlResult result = hazelcastInstance.getSql().execute("SELECT name FROM emp WHERE age < ?", 30)) {
    for (SqlRow row : result) {
        String name = row.getObject(0);

        System.out.println(name);
    }
}
----

You can run the same code snippet from a member or a client.

=== Querying IMap

The following subsections describe how you can access Hazelcast map objects
and perform queries on them.

==== Names

The SQL service exposes `IMap` objects as tables in the predefined `partitioned`
schema using exact names. This schema is in the SQL service search path so that
you can access the `IMap` objects with or without the schema name.

Schema and table names are case-sensitive; you can access the `employee` map, for example,
as `employee` or `partitioned.employee`, but not as `Employee`:

[source,sql]
----
SELECT * FROM employee
SELECT * FROM partitioned.employee
----

==== Fields

The SQL service resolves fields accessible from the SQL automatically. The
service reads the first local entry pair of the `IMap` to construct the
list of fields. If the `IMap` does not have local entries on the member where
the query is started, then the list of fields cannot be resolved, and an
exception is thrown.

Field names are case-sensitive.

===== Key and Value Objects

An `IMap` entry consists of a key and a value. These are accessible
through the `__key` and `this` aliases. The following query returns
the keys and values of all entries in a map:

[source,sql]
----
SELECT __key, this FROM employee
----

===== Key and Value Fields

You may also access the nested fields of a key or a value. The list of exposed
fields depends on the serialization format, as described below:

* For Java objects (`Serializable`, `DataSerializable`, `IdentifiedDataSerializable`),
the object is deserialized if needed and then analyzed using the reflection mechanism. Only public
fields and getters are taken into account. A public field is exposed using its exact name.
A getter is exposed using the JavaBean naming conventions.
* For `Portable` objects, the fields that are written in the `Portable.writePortable`
method are exposed using their exact names.
* `HazelcastJsonValue` objects cannot be queried at the moment. This limitation will be
removed in future releases.

Consider the `Employee` class from the example above; the SQL service can access
the following fields:

[cols="1,1"]
|===
| Name
| Type

|`name`
|`VARCHAR`

|`age`
|`INTEGER`
|===

Together with the key and value objects, you may query the following fields from
`IMap<Long, Employee>`:

[source,sql]
----
SELECT __key, this, name, age FROM employee
----

If both the key and value have fields with the same name, then the field of the
value is exposed.

===== "SELECT *" Queries

You may use the `SELECT * FROM <table>` syntax to get all the table fields.

The `__key` and `this` fields are returned by the `SELECT *` queries if they do not
have nested fields. For `IMap<Long, Employee>`, the following query does
not return the `this` field, because the value has nested fields `name` and `age`:

[source,sql]
----
-- Returns __key, name, age
SELECT * FROM employee
----

==== Indexes

The SQL service can use `IMap` indexes to speed up the execution of certain queries.
`SORTED` and `HASH` indexes are supported.

See the <<indexing-queries, Indexing Queries section>> for more information on `IMap`
index creation.

==== High-Density Memory Store

You can query the `IMap` objects with `InMemoryFormat.NATIVE` if they have
at least one index.

See <<configuring-with-system-properties, Configuring with System Properties>> for
more information on setting system properties.

=== Data Types

The SQL service supports a set of SQL data types. Every data type is mapped to a Java
class that represents the type's value.

[cols="1,1", options="header"]
.SQL Data Types
|===
| Type Name
| Java Class

|`BOOLEAN`
|`java.lang.Boolean`

|`VARCHAR`
|`java.lang.String`

|`TINYINT`
|`java.lang.Byte`

|`SMALLINT`
|`java.lang.Short`

|`INTEGER`
|`java.lang.Integer`

|`BIGINT`
|`java.lang.Long`

|`DECIMAL`
|`java.math.BigDecimal`

|`REAL`
|`java.lang.Float`

|`DOUBLE`
|`java.lang.Double`

|`DATE`
|`java.time.LocalDate`

|`TIME`
|`java.time.LocalTime`

|`TIMESTAMP`
|`java.time.LocalDateTime`

|`TIMESTAMP_WITH_TIME_ZONE`
|`java.time.OffsetDateTime`

|`OBJECT`
|Any Java class

|===

=== SELECT

==== Synopsis

[source,sql]
----
SELECT [ * | expression [ [ AS ] expression_alias ] [, ...] ]
FROM table_name [ [ AS ] table_alias ]
[WHERE condition]
----

==== Description

The `SELECT` command retrieves rows from a table. A row is a sequence of expressions defined after the `SELECT` keyword.
Expressions may have optional aliases.

`table_name` refers to a single `IMap` data structure. A table may have an optional alias.

An optional `WHERE` clause defines a `condition`, that is any expression that evaluates to a result of type boolean.
Any row that doesn't satisfy the condition is eliminated from the result.

The following features are *not supported* and are planned for future releases:
`ORDER BY`, `LIMIT`/`OFFSET`, `GROUP BY`/`HAVING`, `JOIN`, set operators (`UNION`, `INTERSECT`, `MINUS`), subqueries.

=== Expressions

Hazelcast SQL supports logical predicates, `IS` predicates, comparison operators, mathematical functions and operators,
string functions, and special functions.

[cols="1,1,1,1", options="header"]
.AND/OR Operators
|===
| `a`
| `b`
| `a AND b`
| `a OR b`

|`TRUE`
|`TRUE`
|`TRUE`
|`TRUE`

|`TRUE`
|`FALSE`
|`FALSE`
|`TRUE`

|`TRUE`
|`NULL`
|`NULL`
|`TRUE`

|`FALSE`
|`FALSE`
|`FALSE`
|`FALSE`

|`FALSE`
|`NULL`
|`FALSE`
|`NULL`

|`NULL`
|`NULL`
|`NULL`
|`NULL`
|===

[cols="1,1", options="header"]
.NOT Operator
|===
| `a`
| `NOT a`

|`TRUE`
|`FALSE`

|`FALSE`
|`TRUE`

|`NULL`
|`NULL`
|===

[cols="1,2,1", options="header"]
.IS Operator
|===
| Predicate
| Description
| Example

|`IS TRUE`
|Evaluates to `TRUE` if the boolean argument is `TRUE`
|`age < 30 IS TRUE`

|`IS NOT TRUE`
|Evaluates to `TRUE` if the boolean argument is `FALSE` or `NULL`
|`age < 30 IS NOT TRUE`

|`IS FALSE`
|Evaluates to `TRUE` if the boolean argument is `FALSE`
|`age < 30 IS FALSE`

|`IS NOT FALSE`
|Evaluates to `TRUE` if the boolean argument is `TRUE` or `NULL`
|`age < 30 IS NOT FALSE`

|`IS NULL`
|Evaluates to `TRUE` if the argument is `NULL`
|`name IS NULL`

|`IS NOT NULL`
|Evaluates to `TRUE` if the argument is not `NULL`
|`name IS NOT NULL`
|===

[cols="1,2,1", options="header"]
.Comparison Operators
|===
| Operator
| Description
| Example

|`=`
|Equal to
|`age = 30`

|`!=` or `<>`
|Not equal to
|`age != 30` or `age <> 30`

|`<`
|Less than
|`age < 30`

|`>`
|Greater than
|`age > 30`

|`\<=`
|Less than or equal to
|`age \<= 30`

|`>=`
|Greater than or equal to
|`age >= 30`
|===

[cols="1,2,1", options="header"]
.Mathematical Operators
|===
| Operator
| Description
| Example

|`+`
|Addition
|`5 + 2`

|`-`
|Subtraction
|`5 - 2`

|`*`
|Multiplication
|`5 * 2`

|`/`
|Division
|`5 / 2`
|===

[cols="1,2,1,1", options="header"]
.Mathematical Functions
|===
| Function
| Description
| Example
| Result

|`ABS(number)`
|Aboslute value of the argument
|`ABS(-5)`
|`5`

|`CEIL(number)`
|The nearest integer greater than or equal to argument
|`CEIL(25.3)`
|`26`

|`DEGREES(double)`
|Convert radians to degrees
|`DEGREES(0.67)`
|`38.38817227376516`

|`EXP(number)`
|Exponential
|`EXP(2.5)`
|`12.182493960703473`

|`FLOOR(number)`
|The nearest integer less than or equal to argument
|`FLOOR(25.3)`
|`25`

|`LN(number)`
|Natural logarithm
|`LN(2.5)`
|`0.9162907318741551`

|`LOG10(number)`
|Base 10 logarithm
|`LOG(2.5)`
|`0.3979400086720376`

|`RADIANS(double)`
|Convert degrees to radians
|`RADIANS(38.39)`
|`0.6700318998406232`

|`RAND`
|Random value in the range [0.0; 1.0)
|`RAND()`
|`0.6324099982812553`

|`RAND(number)`
|Random value in the range [0.0; 1.0) using the given seed
|`RAND(10)`
|`0.7304302967434272`

|`ROUND(number)`
|Round to an integer
|`ROUND(34.5678)`
|`35`

|`ROUND(number, s integer)`
|Round to `s` decimal places
|`ROUND(34.5678, 2)`
|`34.57`

|`SIGN(number)`
|Return -1, 0 or 1 for negative, zero or positive argument, respectively
|`SIGN(-25)`
|`-1`

|`TRUNCATE(number)`
|Truncate to an integer
|`TRUNC(34.5678)`
|`34`

|`TRUNCATE(number, s integer)`
|Truncate to `s` decimal places
|`TRUNC(34.5678, 2)`
|`34.56`

|===

[cols="1,1", options="header"]
.Trigonometric Functions
|===
| Function
| Description

|`ACOS(double)`
|Inverse cosine

|`ASIN(double)`
|Inverse sine

|`ATAN(double)`
|Inverse tangent

|`COS(double)`
|Cosine

|`COT(double)`
|Cotangent

|`SIN(double)`
|Sine

|`TAN(double)`
|Tangent
|===

[cols="1,2,1,1", options="header"]
.String Functions
|===
| Function
| Description
| Example
| Result

|`string \|\| string`
|Concatenate two strings
|`'John' \|\| ' ' \|\| 'Doe'`
|`John Doe`

|`ASCII(string)`
|ASCII code of the first character of the argument
|`ASCII('a')`
|`97`

|`BTRIM(string)`
|Equivalent to `TRIM(BOTH ' ' FROM string)`
|
|

|`INITCAP(string)`
|Convert the first letter of each word to upper case, and the rest to lower case
|`INITCAP('john DOE')`
|`John Doe`

|`LENGTH(string)`
|Length of the string
|`LENGTH('John Doe')`
|`8`

|`LIKE`
|Return `TRUE` if the value string follows the pattern
|`'John Doe' LIKE '%Doe'`
|`TRUE`

|`LIKE ... ESCAPE`
|Return `TRUE` if the value string follows the pattern, escaping a special character in the pattern
|`'text' LIKE '!_ext' ESCAPE '!'`
|`FALSE`

|`LOWER(string)`
|Convert the string to lower case
|`LOWER('John Doe')`
|`john doe`

|`LTRIM(string)`
|Equivalent to `TRIM(LEADING ' ' FROM string)`
|
|

|`RTRIM(string)`
|Equivalent to `TRIM(TRAILING ' ' FROM string)`
|
|

|`SUBSTRING(string FROM integer)`
|Extract substring starting with the given position
|`SUBSTRING('John Doe' FROM 6)`
|`Doe`

|`SUBSTRING(string FROM integer FOR integer)`
|Extract substring starting with the given position for the given length
|`SUBSTRING('John Doe' FROM 1 FOR 4)`
|`John`

|`TRIM([LEADING\|TRAILING\|BOTH] [characters FROM] string)`
|Remove `characters` (a space by default) from the start/end/both ends of the string
|`TRIM(BOTH '[]' FROM '[John Doe]')`
|`John Doe`

|`TRIM(characters FROM string)`
|Equivalent to `TRIM(BOTH characters FROM string)`
|`TRIM('[]' FROM '[John Doe]')`
|`John Doe`

|`TRIM(string)`
|Equivalent to `TRIM(BOTH ' ' FROM string)`
|`TRIM(' John Doe ')`
|`John Doe`

|`UPPER(string)`
|Convert the string to upper case
|`UPPER('John Doe')`
|`JOHN DOE`
|===

[cols="1,2,1", options="header"]
.Special Functions
|===
| Function
| Description
| Example

|`CAST(value AS type)`
|Convert the value to the given type
|`CAST(age AS VARCHAR)`
|===

=== Lite Members

You cannot start SQL queries on lite members. This limitation will be removed in
future releases.

=== How Distributed SQL Works

When an SQL statement is submitted for execution, the SQL service parses and
optimizes it using Apache Calcite. The result is an executable plan that
is cached and reused by subsequent executions of the same statement.

The plan contains a tree of query fragments. A query fragment is a tree of
operators that could be executed on a single member independently. Child
fragments supply data to parent fragments, possibly over a network, until
the root fragment is reached. The root fragment returns the query results.
