
[[getting-started]]
== Quick Start

This chapter intends to get you started in 5 minutes. The quick start shows how to
start Hazelcast members, form a cluster, connect it with
a client application in your preferred language and monitor
the cluster using Hazelcast Management Center.

For a comprehensive overview of what Hazelcast IMDG actually is
see <<what-is-hazelcast-imdg>>.

=== Installing

As a prerequisite, make sure you have link:https://www.oracle.com/java/technologies/javase-downloads.html[Java^]
installed on your system. If you prefer to use Docker to start Hazelcast members, make sure it is also installed;
see its link:https://www.docker.com/products/docker-desktop[download^] page.

To download and install Hazelcast:

* go to the link:https://hazelcast.org/imdg/download/[Downloads^] page
* download your preferred package (`TAR` or `ZIP`) under the "Server" column
* extract the downloaded package into a directory.

=== Creating a Cluster

You can use the following command on your terminal/command line
to start a standalone Hazelcast member while you are in the extracted directory:

[source,shell,indent=0,subs="verbatim,attributes",role="primary"]
.Linux
----
sh bin/start.sh
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Windows
----
bin/start.bat
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Docker
----
docker run hazelcast/hazelcast:$HAZELCAST_VERSION
----

Now you have a 1-member cluster. To add one more member to the cluster,
open another terminal/command line and rerun the above command. The members
discover each other automatically and form a 2-member cluster. Note that these
members are started with the default configuration, i.e., `hazelcast.xml` located
at the `bin` directory.

=== Your First Client Application

Having a running cluster as started in the above section, let's
create a client application that connects to this cluster,
creates a map and populates it. Below, we first briefly give
how to install a client of your preference and then an example code
for each. We are assuming that the members and clients are on the
same machine for simplicity.

[source,java,indent=0,subs="verbatim,attributes",role="primary"]
.Java
----
//Installation notes: There is no need for a separate installation.

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class MapSample {
    public static void main(String[] args) {
        // Start the client and connect to the cluster
        HazelcastInstance hz = HazelcastClient.newHazelcastClient();
        // Create a Distributed Map in the cluster
        IMap map = hz.getMap("my-distributed-map");
        //Standard Put and Get
        map.put("1", "John");
        map.put("2", "Mary");
        map.put("3", "Jane");
        // Shutdown the client
        hz.shutdown();
    }
}
----

[source,c++,indent=0,subs="verbatim,attributes",role="secondary"]
.C++
----
//Installation notes: Download the latest C++ library from
//https://hazelcast.org/imdg/clients-languages/cplusplus/
//and see https://github.com/hazelcast/hazelcast-cpp-client#13-downloading-and-installing]
//for installation instructions.

#include 

using namespace hazelcast::client;
int main() {
    // Start the client and connect to the cluster
    HazelcastClient hz;
    // Create a Distributed Map in the cluster
    IMap map = hz.getMap("my-distributed-map");
    //Standard Put and Get
    map.put("1", "John");
    map.put("2", "Mary");
    map.put("3", "Jane");
    // Shutdown the client
    hz.shutdown();

    return 0;
}
----

[source,java,indent=0,subs="verbatim,attributes",role="secondary"]
.C#
----
//Installation notes: Run the following command at the NuGet package manager console
//Install-Package Hazelcast.Net -Pre

using Hazelcast.Client;

namespace Hazelcast.Examples.Org.Website.Samples
{
    public class MapSample
    {
        public static void Run(string[] args)
        {
            // Start the client and connect to the cluster
            var hz = HazelcastClient.NewHazelcastClient();
            // Create a Distributed Map in the cluster
            var map = hz.GetMap("my-distributed-map");
            //Standard Put and Get
            map.put("1", "John");
            map.put("2", "Mary");
            map.put("3", "Jane");
            // Shutdown the client
            hz.Shutdown();
        }
    }
}
----

[source,javascript,indent=0,subs="verbatim,attributes",role="secondary"]
.Node.js
----
//Installation notes: Run the following command
//npm install hazelcast-client

var Client = require('hazelcast-client').Client;
// Start the client and connect to the cluster
Client.newHazelcastClient().then(function (hz) {
    var map;
    // Create a Distributed Map in the cluster
    hz.getMap('my-distributed-map').then(function (mp) {
        map = mp;
        // Standard Put and Get
        return map.put('1', 'John');
    });
        // Shutdown the client
        hz.shutdown();
    });
});
----

[source,python,indent=0,subs="verbatim,attributes",role="secondary"]
.Python
----
# Installation notes: Run the following command
# pip install hazelcast-python-client

import hazelcast

if __name__ == "__main__":
    # Start the client and connect to the cluster
    hz = hazelcast.HazelcastClient()
    # Create a Distributed Map in the cluster
    map = hz.get_map("my-distributed-map").blocking()
    # Standard Put and Get
    map.put("1", "John")
    map.put("2", "Mary")
    map.put("3", "Jane")
    # Shutdown the client
    hz.shutdown()
----

[source,go,indent=0,subs="verbatim,attributes",role="secondary"]
.Go
----
//Installation notes: Run the following command
//go get github.com/hazelcast/hazelcast-go-client

import "github.com/hazelcast/hazelcast-go-client"

func mapSampleRun() {
	// Start the client and connect to the cluster
	hz, _ := hazelcast.NewClient()
	// Create a Distributed Map in the cluster
	mp, _ := hz.GetMap("myDistributedMap")
	//Standard Put and Get
	mp.Put("1", "John")
	mp.Put("2", "Mary")
	mp.Put("3", "Jane")
	// Shutdown the client
	hz.Shutdown()
} 
----

For comprehensive information on the clients, see the following sections:

* <<java-client, Java client>>
* link:https://github.com/hazelcast/hazelcast-cpp-client[C++ client]
* link:https://github.com/hazelcast/hazelcast-csharp-client[C# client]
* link:https://github.com/hazelcast/hazelcast-nodejs-client[Node.js client]
* link:https://github.com/hazelcast/hazelcast-python-client[Python client]
* link:https://github.com/hazelcast/hazelcast-go-client[Go client]

=== Connecting Management Center to the Cluster

Hazelcast Management Center helps you to monitor and manage your IMDG cluster.
After you created your cluster and client application as depicted in the above sections,
let's connect Management Center to the cluster. Note that having client applications
is not a must to use the Management Center; you can connect it to your cluster that
does not have any clients.

Management Center comes with the Hazelcast IMDG download package.

Use the following scripts to start the Management Center service first. In case you are
using Docker, run the related command shown below.

[source,shell,indent=0,subs="verbatim,attributes",role="primary"]
.Linux
----
management-center/start.sh
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Windows
----
management-center/start.bat
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Docker
----
docker run -p 8080:8080 hazelcast/management-center
----

Then, open your preferred web browser to `\http://localhost:8080` and
select the `default` security provider to provide a username and password.
Log in to Management Center using those credentials and create a cluster connection;
the defaults should work fine. If using Docker for members, find out the Docker IP address
of cluster rather than the default of localhost.

For comprehensive information on Management Center, see its
link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html[documentation^].
