
[[getting-started]]
== Quick Start

This chapter briefly describes Hazelcast IMDG and
covers a basic installation and quick start through which
you start Hazelcast members, form a cluster, connect it with
a client application in your preferred language and monitor
the cluster using Hazelcast Management Center.

=== What is Hazelcast IMDG?

Hazelcast IMDG is an open-source distributed in-memory
object store supporting a wide variety of data structures.

You can use Hazelcast IMDG to store your data in RAM, spread
and replicate it across your cluster of machines, and perform computations on it.
Replication gives you the resilience to failures of cluster members.

Hazelcast IMDG is highly scalable and available. Distributed applications can use
it for distributed caching, synchronization, clustering, processing,
pub/sub messaging, etc.

It is implemented in Java language and has clients for Java, C++, .NET, REST, Python,
Go and Node.js. Hazelcast IMDG also speaks Memcached and REST protocols. It plugs into
Hibernate and can easily be used with any existing database system.

Hazelcast IMDG makes distributed computing simple by
offering distributed implementations of many developer-friendly interfaces.
For example, the Map interface provides an In-Memory Key Value store which confers many
of the advantages of NoSQL in terms of developer friendliness and developer productivity.

Your cloud-native applications can easily use Hazelcast IMDG.
It is flexible enough to use as a data and computing platform out-of-the-box
or as a framework for your own cloud-native applications and microservices.

Hazelcast IMDG is designed to be lightweight and easy to use. Since it
is delivered as a compact library (JAR) and
has no external dependencies other than Java, it easily
plugs into your software solution and provides
distributed data structures and computing utilities.

It is designed to scale up to hundreds of members and thousands of clients.
When you add new members, they automatically discover the cluster
and linearly increase both the memory and
processing capacity. The members maintain a TCP connection between
each other and all communication is performed through
this layer. Each cluster member is configured to be the same in terms
of functionality. The oldest member (the first member created
in the cluster) automatically performs the data assignment to cluster members.
If the oldest member dies, the second oldest member takes over.

NOTE: You can come across with the term "master" or "master member" in some
sections of this manual. They are used for contextual clarification purposes;
please remember that they refer to the "oldest member" which is explained in
the above paragraph.

Hazelcast IMDG offers simple scalability, partitioning (sharding), and re-balancing
out-of-the-box. It does not require any extra coordination processes. NoSQL and
traditional databases are difficult to scale out and manage. They require additional
processes for coordination and high availability. With Hazelcast IMDG, when you start
another process to add more capacity, data and backups are automatically and evenly balanced.

**Hazelcast's Distinctive Strengths**

* It is open source.
* It is only a JAR file. You do not need to install software other than Java.
* Hazelcast IMDG stores everything in-memory (RAM). It is designed to perform fast reads
and updates.
* Hazelcast IMDG is peer-to-peer; there is no single point of failure in a Hazelcast IMDG cluster;
each member in the cluster is configured to be functionally the same. They all store equal amounts
of data and do equal amounts of processing. You can embed Hazelcast IMDG in your
existing application or use it in client and server mode where your application is a
client to Hazelcast members.
* When the size of your memory and compute requirements increase, new members can
be dynamically joined to the Hazelcast IMDG cluster to scale elastically.
* Data is resilient to member failure. Data backups are distributed across the cluster.
This is a big benefit when a member in the cluster crashes as data is not lost.
Hazelcast keeps the backup of each data entry on multiple members. On a member
failure, the data is restored from the backup and the cluster continues to operate without downtime.
* Members are always aware of each other unlike in traditional key-value caching solutions.
* Hazelcast provides out-of-the-box distributed data structures.

Finally, Hazelcast has a vibrant open source community enabling it to be continuously developed.

Hazelcast is a fit when you need:

* analytic applications requiring big data processing by partitioning the data
* to retain frequently accessed data in the grid
* a cache, particularly an open source JCache provider with elastic distributed
scalability
* a primary data store for applications with utmost performance, scalability and
low-latency requirements
* an In-Memory NoSQL Key Value Store
* publish/subscribe communication at highest speed and scalability between applications
* applications that need to scale elastically in distributed and cloud environments
* a highly available distributed cache for applications
* an alternative to Coherence and Terracotta.

=== Installing

As a prerequisite, make sure you have link:https://www.oracle.com/java/technologies/javase-downloads.html[Java^]
installed on your system. If you prefer to use Docker to start Hazelcast members, make sure it is also installed;
see its link:https://www.docker.com/products/docker-desktop[download^] page.

To download and install Hazelcast:

* go to the link:https://hazelcast.org/imdg/download/[Downloads^] page
* download your preferred package (`TAR` or `ZIP`) under the "Server" column
* extract the downloaded package into a directory.

=== Creating a Cluster

You can use the following command on your terminal/command line
to start a standalone Hazelcast member while you are in the extracted directory:

[source,shell,indent=0,subs="verbatim,attributes",role="primary"]
.Linux
----
sh bin/start.sh
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Windows
----
bin/start.bat
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Docker
----
docker run hazelcast/hazelcast:$HAZELCAST_VERSION
----

Now you have a 1-member cluster. To add one more member to the cluster,
open another terminal/command line and rerun the above command. The members
discover each other automatically and form a 2-member cluster. Note that these
members are started with the default configuration, i.e., `hazelcast.xml` located
at the `bin` directory.

=== Your First Client Application

Having a running cluster as started in the above section, let's
create a client application that connects to this cluster,
creates a map and populates it. Below, we first briefly give
how to install a client of your preference and then an example code
for each. We are assuming that the members and clients are on the
same machine for simplicity.

[source,java,indent=0,subs="verbatim,attributes",role="primary"]
.Java
----
//Installation notes: There is no need for a separate installation.

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class MapSample {
    public static void main(String[] args) {
        // Start the client and connect to the cluster
        HazelcastInstance hz = HazelcastClient.newHazelcastClient();
        // Create a Distributed Map in the cluster
        IMap map = hz.getMap("my-distributed-map");
        //Standard Put and Get
        map.put("1", "John");
        map.put("2", "Mary");
        map.put("3", "Jane");
        // Shutdown the client
        hz.shutdown();
    }
}
----

[source,c++,indent=0,subs="verbatim,attributes",role="secondary"]
.C++
----
//Installation notes: Download the latest C++ library from
//https://hazelcast.org/imdg/clients-languages/cplusplus/
//and see https://github.com/hazelcast/hazelcast-cpp-client#13-downloading-and-installing]
//for installation instructions.

#include 

using namespace hazelcast::client;
int main() {
    // Start the client and connect to the cluster
    HazelcastClient hz;
    // Create a Distributed Map in the cluster
    IMap map = hz.getMap("my-distributed-map");
    //Standard Put and Get
    map.put("1", "John");
    map.put("2", "Mary");
    map.put("3", "Jane");
    // Shutdown the client
    hz.shutdown();

    return 0;
}
----

[source,java,indent=0,subs="verbatim,attributes",role="secondary"]
.C#
----
//Installation notes: Run the following command at the NuGet package manager console
//Install-Package Hazelcast.Net -Pre

using Hazelcast.Client;

namespace Hazelcast.Examples.Org.Website.Samples
{
    public class MapSample
    {
        public static void Run(string[] args)
        {
            // Start the client and connect to the cluster
            var hz = HazelcastClient.NewHazelcastClient();
            // Create a Distributed Map in the cluster
            var map = hz.GetMap("my-distributed-map");
            //Standard Put and Get
            map.put("1", "John");
            map.put("2", "Mary");
            map.put("3", "Jane");
            // Shutdown the client
            hz.Shutdown();
        }
    }
}
----

[source,javascript,indent=0,subs="verbatim,attributes",role="secondary"]
.Node.js
----
//Installation notes: Run the following command
//npm install hazelcast-client

var Client = require('hazelcast-client').Client;
// Start the client and connect to the cluster
Client.newHazelcastClient().then(function (hz) {
    var map;
    // Create a Distributed Map in the cluster
    hz.getMap('my-distributed-map').then(function (mp) {
        map = mp;
        // Standard Put and Get
        return map.put('1', 'John');
    });
        // Shutdown the client
        hz.shutdown();
    });
});
----

[source,python,indent=0,subs="verbatim,attributes",role="secondary"]
.Python
----
# Installation notes: Run the following command
# pip install hazelcast-python-client

import hazelcast

if __name__ == "__main__":
    # Start the client and connect to the cluster
    hz = hazelcast.HazelcastClient()
    # Create a Distributed Map in the cluster
    map = hz.get_map("my-distributed-map").blocking()
    # Standard Put and Get
    map.put("1", "John")
    map.put("2", "Mary")
    map.put("3", "Jane")
    # Shutdown the client
    hz.shutdown()
----

[source,go,indent=0,subs="verbatim,attributes",role="secondary"]
.Go
----
//Installation notes: Run the following command
//go get github.com/hazelcast/hazelcast-go-client

import "github.com/hazelcast/hazelcast-go-client"

func mapSampleRun() {
	// Start the client and connect to the cluster
	hz, _ := hazelcast.NewClient()
	// Create a Distributed Map in the cluster
	mp, _ := hz.GetMap("myDistributedMap")
	//Standard Put and Get
	mp.Put("1", "John")
	mp.Put("2", "Mary")
	mp.Put("3", "Jane")
	// Shutdown the client
	hz.Shutdown()
} 
----

For comprehensive information on the clients, see the following sections:

* <<java-client, Java client>>
* link:https://github.com/hazelcast/hazelcast-cpp-client[C++ client]
* link:https://github.com/hazelcast/hazelcast-csharp-client[C# client]
* link:https://github.com/hazelcast/hazelcast-nodejs-client[Node.js client]
* link:https://github.com/hazelcast/hazelcast-python-client[Python client]
* link:https://github.com/hazelcast/hazelcast-go-client[Go client]

=== Connecting Management Center to the Cluster

Hazelcast Management Center helps you to monitor and manage your IMDG cluster.
After you created your cluster and client application as depicted in the above sections,
let's connect Management Center to the cluster. Note that having client applications
is not a must to use the Management Center; you can connect it to your cluster that
does not have any clients.

Management Center comes with the Hazelcast IMDG download package.

Use the following scripts to start the Management Center service first. In case you are
using Docker, run the related command shown below.

[source,shell,indent=0,subs="verbatim,attributes",role="primary"]
.Linux
----
management-center/start.sh
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Windows
----
management-center/start.bat
----

[source,shell,indent=0,subs="verbatim,attributes",role="secondary"]
.Docker
----
docker run -p 8080:8080 hazelcast/management-center
----

Then, open your preferred web browser to `\http://localhost:8080` and
select the `default` security provider to provide a username and password.
Log in to Management Center using those credentials and create a cluster connection;
the defaults should work fine. If using Docker for members, find out the Docker IP address
of cluster rather than the default of localhost.

For comprehensive information on Management Center, see its
link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html[documentation^].
