
[[getting-started]]
== Quick Start

This chapter intends to get you started in 5 minutes. The quick start shows how to
start Hazelcast members, form a cluster, connect it with
a client application in your preferred language and monitor
the cluster using Hazelcast Management Center.

For a comprehensive overview of what Hazelcast IMDG actually is
see <<what-is-hazelcast-imdg>>.

=== Installing

You can use the Hazelcast
link:https://github.com/hazelcast/hazelcast-command-line[Command Line Interface (CLI)^]
to install and start Hazelcast IMDG.

Run the following commands to install Hazelcast CLI:

[source,bash,indent=0,subs="verbatim,attributes",role="primary"]
.Homebrew
----
$ brew tap hazelcast/hz
$ brew install hazelcast
----

[source,bash,indent=0,subs="verbatim,attributes",role="secondary"]
.Debian
----
$ wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
$ echo "deb https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
$ sudo apt update && sudo apt install hazelcast
----

[source,bash,indent=0,subs="verbatim,attributes",role="secondary"]
.RPM
----
$ wget https://repository.hazelcast.com/rpm/hazelcast-rpm.repo -O hazelcast-rpm.repo
$ sudo mv hazelcast-rpm.repo /etc/yum.repos.d/
$ sudo yum install hazelcast
----

After the installation of Hazelcast CLI, the package managers
will display the installation directory and usage information.

Currently, the CLI way is meant for development purposes, not for a production usage.
For production or if you prefer other ways, take a look at <<installing-hazelcast-imdg>>.

=== Creating a Cluster

Use the following command on your terminal/command line
to start a standalone Hazelcast member:

[source,bash,subs="attributes+"]
----
$ hz start
----

Now you have a 1-member cluster. To add one more member to the cluster,
open another terminal/command line and rerun the above command. The members
discover each other automatically and form a 2-member cluster. You should see
happening it with log output in the command line like:

[source,bash,subs="attributes+"]
----
Members {size:2, ver:2} [
    Member [127.0.0.1]:5701 - e40081de-056a-4ae5-8ffe-632caf8a6cf1 this
    Member [127.0.0.1]:5702 - 93e82109-16bf-4b16-9c87-f4a6d0873080
]
----

Note that these members are started with the default configuration.
The location of the `hazelcast.xml` is printed on the first line of
the output of the above command.

=== Your First Client Application

Having a running cluster as started in the above section, let's
create a client application that connects to this cluster,
creates a map and populates it. Below, we first briefly give
how to install a client of your preference and then an example code
for each. We are assuming that the members and clients are on the
same machine for simplicity.

[source,java,indent=0,subs="verbatim,attributes",role="primary"]
.Java
----
// Installation notes: You have to have Hazelcast Java Client on the classpath.
// The simplest way of doing it is to put `hazelcast-all` JAR
// on the classpath, e.g. via Maven. See "Installation" chapter for details.

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class MapSample {
    public static void main(String[] args) {
        // Start the client and connect to the cluster
        HazelcastInstance hz = HazelcastClient.newHazelcastClient();
        // Create a Distributed Map in the cluster
        IMap map = hz.getMap("my-distributed-map");
        //Standard Put and Get
        map.put("1", "John");
        map.put("2", "Mary");
        map.put("3", "Jane");
        // Shutdown the client
        hz.shutdown();
    }
}
----

[source,c++,indent=0,subs="verbatim,attributes",role="secondary"]
.C++
----
//Installation notes: Download the latest C++ library from
//https://hazelcast.org/imdg/clients-languages/cplusplus/
//and see https://github.com/hazelcast/hazelcast-cpp-client#13-downloading-and-installing]
//for installation instructions.

#include 

using namespace hazelcast::client;
int main() {
    // Start the client and connect to the cluster
    HazelcastClient hz;
    // Create a Distributed Map in the cluster
    IMap map = hz.getMap("my-distributed-map");
    //Standard Put and Get
    map.put("1", "John");
    map.put("2", "Mary");
    map.put("3", "Jane");
    // Shutdown the client
    hz.shutdown();

    return 0;
}
----

[source,java,indent=0,subs="verbatim,attributes",role="secondary"]
.C#
----
//Installation notes: Run the following command at the NuGet package manager console
//Install-Package Hazelcast.Net -Pre

using Hazelcast.Client;

namespace Hazelcast.Examples.Org.Website.Samples
{
    public class MapSample
    {
        public static void Run(string[] args)
        {
            // Start the client and connect to the cluster
            var hz = HazelcastClient.NewHazelcastClient();
            // Create a Distributed Map in the cluster
            var map = hz.GetMap("my-distributed-map");
            //Standard Put and Get
            map.put("1", "John");
            map.put("2", "Mary");
            map.put("3", "Jane");
            // Shutdown the client
            hz.Shutdown();
        }
    }
}
----

[source,javascript,indent=0,subs="verbatim,attributes",role="secondary"]
.Node.js
----
//Installation notes: Run the following command
//npm install hazelcast-client

var Client = require('hazelcast-client').Client;
// Start the client and connect to the cluster
Client.newHazelcastClient().then(function (hz) {
    var map;
    // Create a Distributed Map in the cluster
    hz.getMap('my-distributed-map').then(function (mp) {
        map = mp;
        // Standard Put and Get
        return map.put('1', 'John');
    });
        // Shutdown the client
        hz.shutdown();
    });
});
----

[source,python,indent=0,subs="verbatim,attributes",role="secondary"]
.Python
----
# Installation notes: Run the following command
# pip install hazelcast-python-client

import hazelcast

if __name__ == "__main__":
    # Start the client and connect to the cluster
    hz = hazelcast.HazelcastClient()
    # Create a Distributed Map in the cluster
    map = hz.get_map("my-distributed-map").blocking()
    # Standard Put and Get
    map.put("1", "John")
    map.put("2", "Mary")
    map.put("3", "Jane")
    # Shutdown the client
    hz.shutdown()
----

[source,go,indent=0,subs="verbatim,attributes",role="secondary"]
.Go
----
//Installation notes: Run the following command
//go get github.com/hazelcast/hazelcast-go-client

import "github.com/hazelcast/hazelcast-go-client"

func mapSampleRun() {
	// Start the client and connect to the cluster
	hz, _ := hazelcast.NewClient()
	// Create a Distributed Map in the cluster
	mp, _ := hz.GetMap("myDistributedMap")
	//Standard Put and Get
	mp.Put("1", "John")
	mp.Put("2", "Mary")
	mp.Put("3", "Jane")
	// Shutdown the client
	hz.Shutdown()
} 
----

For comprehensive information on the clients, see the following sections:

* <<java-client, Java client>>
* link:https://github.com/hazelcast/hazelcast-cpp-client[C++ client]
* link:https://github.com/hazelcast/hazelcast-csharp-client[C# client]
* link:https://github.com/hazelcast/hazelcast-nodejs-client[Node.js client]
* link:https://github.com/hazelcast/hazelcast-python-client[Python client]
* link:https://github.com/hazelcast/hazelcast-go-client[Go client]

=== Connecting Management Center to the Cluster

Hazelcast Management Center helps you to monitor and manage your IMDG cluster.
After you created your cluster and client application as depicted in the above sections,
let's connect Management Center to the cluster. Note that having client applications
is not a must to use the Management Center; you can connect it to your cluster that
does not have any clients.

Use the following command to start the Management Center:

[source,bash,subs="attributes+"]
----
hz mc start
----

Then, open your preferred web browser to `\http://localhost:8080` and
select the `default` security provider to provide a username and password.
Log in to Management Center using those credentials and create a cluster connection;
the defaults should work fine. If using Docker for members, find out the Docker IP address
of cluster rather than the default of localhost.

For comprehensive information on Management Center, see its
link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html[documentation^].

=== What's Next?

In this chapter, you have learnt starting a Hazelcast IMDG cluster,
inserting data to it via clients and monitoring
it through Management Center. Now, you may want to perform the following:

* Form a cluster not just on your local machine: see <<setting-up-clusters>>.
* Start using our distributed data structures: see <<distributed-data-structures>>.
* Learn how to configure Hazelcast IMDG: see <<understanding-configuration>>.

You can always reach out via link:https://slack.hazelcast.com/[Slack^],
link:https://groups.google.com/forum/#!forum/hazelcast[Mail Group^] or link:http://www.stackoverflow.com[StackOverflow^].
