
[appendix]
== hazelcast-member Tool

The `hazelcast-member` tool is a command line utility that can run one or more Hazelcast IMDG members on the local machine. Below sections provide its installation instructions for various platforms and usage details.

The tool is open source. You can find its source code along with a brief documentation at its GitHub https://github.com/hazelcast/hazelcast-member-tool[repo].

=== Installing the Tool

The `hazelcast-member` tool is packaged in `yum` for Red Hat and CentOS, `apt` for Debian and Ubuntu, and `brew` for Mac OS X. See the below sections for installation details.

==== On Mac OS X

If you have brew installed, run the following commands to install this tool:

[source,plain]
----
brew tap hazelcast/homebrew-hazelcast
brew install hazelcast-member
----

[NOTE]
====
Make sure that Apple Xcode is installed on the machine. If not, you will get an `xcrun` error while the `brew tap` command shown above is running. To have the Xcode, run the following commands in the shown order:

[source,plain]
----
xcode-select --install
xcode-select --reset
----
====

==== On Ubuntu and Debian

To resolve the `DEB` artifacts from Bintray, follow the below instructions.

. Import the Bintray's GPG key using the following command:
+
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
```
+
. Run the following commands to add the `DEB` artifact to your system configuration file and update the lists of packages:
+
```
echo "deb https://dl.bintray.com/hazelcast/deb stable main" | sudo tee -a /etc/apt/sources.list
sudo apt-get update
``` 
+
. Run the following command to install the `hazelcast-member` tool:
+
```
sudo apt-get install hazelcast-member
```

==== On Red Hat and CentOS

To resolve the `RPM` artifacts from Bintray, follow the below instructions.

. Run the following command to get a generated `.repo` file:
+
```
wget https://bintray.com/hazelcast/rpm/rpm -O bintray-hazelcast-rpm.repo
```
+
. Install the `.repo` file using the following command:
+
```
sudo mv bintray-hazelcast-rpm.repo /etc/yum.repos.d/
```
+
. Run the following command to install the `hazelcast-member` tool:
+
```
sudo yum install hazelcast-member
```

=== Using the Tool

After successfully installing the `hazelcast-member` tool, you can perform the operations described below.

Note that you can always display the brief usage descriptions using `hazelcast-member -h`. You can also get information on the commands described below using `hazelcast-member help <command>`.

==== Starting Members

Run the following command to start a Hazelcast IMDG member:

```
hazelcast-member start
```

As soon as you run the command, it shows you a name assigned to the process ID which corresponds to the newly started Hazelcast member. An example output is shown below:

```
john@Johns-MacBook-Pro:~/Desktop$ hazelcast-member start
ID:  confident_tharp
```

The process naming (`confident_tharp` in the above example) is for your convenience so that you can easily remember the member's name. The tool chooses the member names from a `JAR` file that comes with the tool (`mobynames-1.0.jar`). As you start other members, you will see different names for each of them. You can start as many members as you want using the above `hazelcast-member start` command.

When you start a member using this tool, it starts with the default configuration (`hazelcast.xml`) that comes with the tool.

You can use the arguments described below for the `start` command:

* `-c` or `--config` `<file>`: If you want to start a member with a customized configuration, use this argument. We do not recommend editing the `hazelcast.xml` file directly since it acts as a configuration template. You can create a copy of it for specifying custom configurations. An example usage is shown below:
+
```
hazelcast-member start -c myOwnConfiguration.xml
```
+
See the <<understanding-configuration, Understanding Configuration chapter>> to learn about Hazelcast IMDG configuration concepts.
* `-cn` or `--cluster-name` `<name>`: You can specify a name for your cluster(s). When you start multiple members having the same cluster name, they form a cluster group. You can create multiple clusters with different names. If you do not specify any cluster name, the tool uses the default one which is `dev`. An example usage is shown below:
+
```
hazelcast-member start -cn my-testing-cluster
```
+
See the <<creating-cluster-groups, Creating Cluster Groups section>> for more information.
* `-cp` or `--cluster-password` `<password>`: You can specify a password for your cluster group(s). If you do not specify any password, the tool uses the default one which is `password`. An example usage is shown below:
+
```
hazelcast-member start -cp testPwd
```
* `-fg` or `--foreground`: If you want the members not to run at the background, use this argument when you start them.
* `-i` or `--interface` `<interface>`: You can specify the network interfaces that your members should use. If not specified, the members will bind to all interfaces of your machine. An example usage is shown below:
+
```
hazelcast-member start -i 10.3.16.4-18
```
* `-j` or `--jar` `<path>`: You can specify the path to your Hazelcast `JAR`. ???
* `-p` or `--port` `<port>`: You can bind your members to a specific port using this argument. If not specified, the tool uses the default one which is 5701.
* `-v` or `--verbose`: It can be used to show more information on the terminal while starting a member. A sample output is shown below:
+
```
Java executable: /usr/bin/java
JAVA_OPTS= -Dgroup.name=dev -Dgroup.password=dev-pass -Dnetwork.interface= -Dinterfaces.enabled=false -Dbind.any=true -Dnetwork.port=5701 -Dhazelcast.config=/usr/local/etc/hazelcast/hazelcast.xml
CLASSPATH=/usr/local/Cellar/hazelcast-member/3.11.0/libexec/lib/hazelcast-all-3.11.jar
Hazelcast config: /usr/local/etc/hazelcast/hazelcast.xml
ID:  hungry_jepsen
PID file for this Hazelcast member: /usr/local/var/run/hazelcast/hungry_jepsen/hazelcast.pid
Permanent logfile for this Hazelcast member: /usr/local/var/log/hazelcast/hungry_jepsen/hazelcast.log
Command line: /usr/bin/java -server  -Dgroup.name=dev -Dgroup.password=dev-pass -Dnetwork.interface= -Dinterfaces.enabled=false -Dbind.any=true -Dnetwork.port=5701 -Dhazelcast.config=/usr/local/etc/hazelcast/hazelcast.xml com.hazelcast.core.server.StartServer
PID: 53416
```
* `-J` or `--JAVA_OPTS` `<options>`: You can use this argument when you want to provide a value for a specific Hazelcast configuration element(s) included in the `hazelcast.xml` file. An example usage is shown below:
+
```
hazelcast-member start -J -Dnetwork.port=5800
```

==== Displaying Member List

Run the following command to see the names of the members you have started:

```
hazelcast-member list
```

It lists the member names as shown below:

```
john@Johns-MacBook-Pro:~/Desktop$ hazelcast-member list
confident_tharp
silly_merkle
```

==== Displaying Member Status

Run the following command to see the status of the members:

```
hazelcast-member status
```

It outputs the member names, their process IDs and status as shown below.


```
john@Johns-MacBook-Pro:~/Desktop$ hazelcast-member status
ID                      PID     STATUS  
confident_tharp         53789   Running
silly_merkle            53684   Running
```

You can also display a specific member's status by providing its name to the command:

```
hazelcast-member status confident_tharp
```


==== Displaying Member Logs

Run the following command to see the logs of a member:

```
hazelcast-member logs
```

It outputs information including the status and member's IP address. A sample output is shown below.

```
INFO: [10.216.1.68]:5701 [dev] [3.11] [10.216.1.68]:5701 is STARTING
Dec 06, 2018 11:37:38 AM com.hazelcast.internal.cluster.ClusterService
INFO: [10.216.1.68]:5701 [dev] [3.11] 

Members {size:1, ver:1} [
	Member [10.216.1.68]:5701 - 2dc4791c-e1b0-4d15-bad9-eea934c32216 this
]

Dec 06, 2018 11:37:38 AM com.hazelcast.core.LifecycleService
INFO: [10.216.1.68]:5701 [dev] [3.11] [10.216.1.68]:5701 is STARTED
```

If you have started more than one members, you need to provide the name of the member, whose logs you want to see, in the logs command:

```
hazelcast-member logs confident_tharp
```

==== Stopping a Member

Run the following command to stop a member:

```
hazelcast-member stop 
```

Note that the above command works if you have only one active member. When you have more than one active members, you need to provide the member name to the command:

```
hazelcast-member stop confident_tharp
```

==== Displaying Hazelcast IMDG Version

Run the following command to display the version of Hazelcast IMDG you are using:

```
hazelcast-member -v
```

You can also use `--version` instead of `-v`.

==== Enabling Command Completion

The `hazelcast-member` tool includes a command completion feature that enables you to use the TAB key to complete a partially typed command. You can enable this feature by adding the following line to your profile (`.bash_profile` or `.profile`):

```
if which hazelcast-member > /dev/null; then eval "$(hazelcast-member init -)"; fi
```

==== Uninstalling the Tool

Run the following commands in the given order to remove the `hazelcast-member` tool from your machine:

```
brew uninstall hazelcast-member
brew untap hazelcast/homebrew-hazelcast
brew cleanup -s
```

