
[appendix]
== Migration Guides

This appendix provides guidelines when upgrading to a new Hazelcast IMDG version.
See also the link:https://docs.hazelcast.org/docs/rn/index.html[release notes^] document
for the changes for each Hazelcast IMDG release.

=== Upgrading to Hazelcast IMDG 4.0

This section provides the guidelines for you
when migrating to Hazelcast IMDG 4.0

==== Removal of Hazelcast Client Module

* The `hazelcast-client` module has been merged into the core module: All the classes
in the `hazelcast-client` module have been moved to `hazelcast`.
`hazelcast-client.jar` will not be created anymore.

==== Changes in Client Configurations

* The `connection-attempt-period` and `connection-attempt-limit`
configuration have been removed. Instead, the elements of
`connection-retry` are now used:

???

???

==== Changes in Custom Attributes

<<custom-attributes, Custom attributes>> are referenced in
predicates, queries and indexes. Some improvements have been
performed in Hazelcast's query engine and one of the results
is the change in custom attribute configurations.

With this change, the following configuration parameters
have been renamed:

**Declarative configuration elements:**

* `extractor` -> `extractor-class-name`

**Programmatic configuration objects and methods:**

* `MapAttributeConfig` -> `AttributeConfig`
* `setExtractor()` -> `setExtractorClassName()`
* `addMapAttributeConfig()` -> `addAttributeConfig()`


See the following table for the before/after samples.

[cols="1a,1a"]
|===

| *_Before IMDG 4.0_* | *_After IMDG 4.0_*

2+|Programmatic Configuration

|

[source,java,options="nowrap"]
----
MapAttributeConfig attributeConfig = new MapAttributeConfig();
attributeConfig.setName("currency");
attributeConfig.setExtractor("com.bank.CurrencyExtractor");

MapConfig mapConfig = new MapConfig();
mapConfig.addMapAttributeConfig(attributeConfig);
----

|

[source,java,options="nowrap"]
----
AttributeConfig attributeConfig = new AttributeConfig();
attributeConfig.setName("currency");
attributeConfig.setExtractorClassName("com.bank.CurrencyExtractor");

MapConfig mapConfig = new MapConfig();
mapConfig.addAttributeConfig(attributeConfig);
----

2+|Declarative Configuration

|

[source,xml,options="nowrap"]
----
<hazelcast>
    ...
    <map name="trades">
        <attributes>
            <attribute extractor="com.bank.CurrencyExtractor">currency</attribute>
        </attributes>
    </map>
    ...
</hazelcast>
----

|

[source,xml,options="nowrap"]
----
<hazelcast>
    ...
    <map name="trades">
        <attributes>
            <attribute extractor-class-name="com.bank.CurrencyExtractor">currency</attribute>
        </attributes>
    </map>
    ...
</hazelcast>
----
|===


==== Removal of MapReduce

MapReduce API has been removed, which was deprecated
since Hazelcast IMDG 3.8. Instead, you can use the
<<fast-aggregations>> on top of Query infrastructure and the
link:https://docs.hazelcast.org/docs/jet/latest/manual/[Hazelcast Jet^]
distributed computing platform as its successors and replacements.

See the following table for the before(MapReduce)/after(Hazelcast Jet)
word count sample.

[cols="1a"]
|===

| *_Before IMDG 4.0 (MapReduce)_*

[source,java]
----
JobTracker tracker = hazelcastInstance.getJobTracker("default");

IMap<String, String> map = hazelcastInstance.getMap(MAP_NAME);
KeyValueSource<String, String> source = KeyValueSource.fromMap(map);

Job<String, String> job = tracker.newJob(source);
ICompletableFuture<Map<String, Integer>> future = job
           .mapper(new TokenizerMapper())
           .combiner(new WordcountCombinerFactory())
           .reducer(new WordcountReducerFactory())
           .submit();

     System.out.println(ToStringPrettyfier.toString(future.get()));
----

| *_After IMDG 4.0 (Hazelcast Jet)_*

[source,java]
----
JobTracker t = hz.getJobTracker("word-count");
IMap<Long, String> documents = hz.getMap("documents");
LongSumAggregation<String, String> aggr = new LongSumAggregation<>();
Map<String, Long> counts =
        t.newJob(KeyValueSource.fromMap(documents))
         .mapper((Long x, String document, Context<String, Long> ctx) ->
                 Stream.of(document.toLowerCase().split("\\W+"))
                       .filter(w -> !w.isEmpty())
                       .forEach(w -> ctx.emit(w, 1L)))
         .combiner(aggr.getCombinerFactory())
         .reducer(aggr.getReducerFactory())
         .submit()
         .get();
----
|===

See the link:https://github.com/hazelcast/hazelcast-jet-code-samples/tree/master/core-api/wordcount-core-api[Jet Code Samples^] for a full insight.

==== Refactoring of Migration Listener

The `MigrationListener` API has been refactored.
With this change, an event is published when a new
migration process starts and another event when migration
is completed. These events include statistics
about the migration process including the start time,
planned migration count, completed migration count, etc.

Additionally, a migration event is published on each replica
migration, both for primary and backup replica migrations.
This event includes the partition ID, replica index and
migration progress statistics.

Before IMDG 4.0, the following were the events listened by
`MigrationListener`:

* `migrationStarted`
* `migrationCompleted`
* `migrationFailed`

After IMDG 4.0, we have the following events instead:

* `migrationStarted`
* `migrationFinished`
* `replicaMigrationCompleted`
* `replicaMigrationFailed`

See the following table for the before/after samples.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
import com.hazelcast.core.MigrationEvent;
import com.hazelcast.core.MigrationListener;

public class ClusterMigrationListener implements MigrationListener {
    @Override
    public void migrationStarted(MigrationEvent migrationEvent) {
        System.err.println("Started: " + migrationEvent);
    }
    @Override
    public void migrationCompleted(MigrationEvent migrationEvent) {
        System.err.println("Completed: " + migrationEvent);
    }
    @Override
    public void migrationFailed(MigrationEvent migrationEvent) {
        System.err.println("Failed: " + migrationEvent);
    }
}
----

| *_After IMDG 4.0_*

[source,java]
----
import com.hazelcast.partition.MigrationListener;
import com.hazelcast.partition.MigrationState;
import com.hazelcast.partition.ReplicaMigrationEvent;

public class ClusterMigrationListener implements MigrationListener {

    @Override
    public void migrationStarted(MigrationState state) {
        System.out.println("Migration Started: " + state);
    }

    @Override
    public void migrationFinished(MigrationState state) {
        System.out.println("Migration Finished: " + state);
    }

    @Override
    public void replicaMigrationCompleted(ReplicaMigrationEvent event) {
        System.out.println("Replica Migration Completed: " + event);
    }

    @Override
    public void replicaMigrationFailed(ReplicaMigrationEvent event) {
        System.out.println("Replica Migration Failed: " + event);
    }
}
----
|===

==== Changes in the Security

===== JAAS Authentication Cleanups

====== Introducing New Principal Types

The `ClusterPrincipal` class representing an authenticated user within the JAAS Subject
has been replaced by three different principal types:

* `ClusterIdentityPrincipal`
* `ClusterRolePrincipal`
* `ClusterEndpointPrincipal`

All these new principal types share the `HazelcastPrincipal` interface so
it is simple to get or remove them all from the subject.

With this change, the `Credentials` object is not referenced from
the principals anymore.

Also, `DefaultPermissionPolicy` which was consuming `ClusterPrincipal`
and also reading the endpoint address from it works with the new
`ClusterRolePrincipals` and `ClusterEndpointPrincipals` principal types.

See the following table for the before/after sample implementations.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
??? old code sample
----

| *_After IMDG 4.0_*

[source,java]
----
??? new code sample
----
|===

====== Changes in ClusterLoginModule

`ClusterLoginModule` in Hazelcast IMDG 3.x contained four
abstract methods to alter the behavior of `LoginModule`:

* `onLogin`
* `onCommit`
* `onAbort`
* `onLogout`

The login module was retrieving `Credentials` and
using it to create the `ClusterPrincipal` back then.

In Hazelcast IMDG 4.0, only `onLogin` is abstract.
Others now have empty implementations. The login module creates
`ClusterEndpointPrincipal` automatically and adds it to the `Subject`.

The `getName()` abstract method has been added. It is used for
constructing `ClusterIdentityPrincipal`. The `addRole(String)` method
can be called by the child implementations to add `ClusterRolePrincipals`
with the given name.

Also, `ClusterLoginModule` introduces three login module options (boolean),
which allows skipping principals of a given type to the JAAS `Subject`.
It allows, for instance, to have just one `ClusterIdentityPrincipal`
in the `Subject` even if there are more login modules in the chain. These
options are:

* `skipIdentity`
* `skipRole`
* `skipEndpoint`.

See the following table for the before/after sample implementations.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
??? old code sample
----

| *_After IMDG 4.0_*

[source,java]
----
??? new code sample
----
|===

====== Changes in Credentials for Client Protocol

In Hazelcast IMDG 3.x, the custom credentials coming through
the client protocol was always automatically deserialized. To
avoid this, the `Credentials` interface has been redesigned in
Hazelcast IMDG 4.0 to contain only the `getName()`
(renamed from `getPrincipal()`) method.
The endpoint handling has been moved out of the interface.

Now, `Credentials` has two new subinterfaces:

* `PasswordCredentials`: The existing `UsernamePasswordCredentials` class
is the default implementation.
* `TokenCredentials`: The new `SimpleTokenCredentials` class has been introduced
to implement it.

`TokenCredentials` is just a holder for byte array, and
the authentication implementations themselves, i.e., custom `LoginModules`,
are responsible for the data deserialization when needed.

The data from client authentication message is not deserialized by Hazelcast members
anymore. For standard authentication, `UsernamePasswordCredentials` is constructed.
For custom authentication, `SimpleTokenCredentials` is constructed.
If the original `Credentials` object is not a `PasswordCredentials`
or `TokenCredentials` instance, then it can be deserialized manually.
However, the deserialization during authentication remains a dangerous
operation and should be avoided.

See the following table for the before/after sample implementations.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
??? old code sample
----

| *_After IMDG 4.0_*

[source,java]
----
??? new code sample
----
|===


NOTE: `Credentials` serialization and deserialization in the member protocol
has not been changed.

====== Changes in JAAS Callbacks

In Hazelcast IMDG 3.x, the `CallbackHandler` implementation `ClusterCallbackHandler`
was only able to work with Hazelcast's `CredentialsCallback`.
In Hazelcast IMDG 4.0, it also works with the standard Java Callback implementations
`NameCallback` and `PasswordCallback`.

`DefaultLoginModule` was using the login module options to retrieve the
member's `Config` object. Now, custom `Callback` types have been
implemented which can be used to retrieve additional data required for
the authentication.

List of the supported ``Callback``s in Hazelcast IMDG 4.0:

* `javax.security.auth.callback.NameCallback`
* `javax.security.auth.callback.PasswordCallback`
* `com.hazelcast.security.CredentialsCallback` (provides access to the incoming `Credentials` instance)
* `com.hazelcast.security.EndpointCallback` (allows retrieving the remote host address, it's a replacement for `Credentials.getEndpoint()` in Hazelcast IMDG 3.x)
* `com.hazelcast.security.ConfigCallback` (allows retrieving member's `Config` object)
* `com.hazelcast.security.SerializationServiceCallback` (provides access to Hazelcast `SerializationService`)

See the following table for the before/after sample implementations.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
??? old code sample
----

| *_After IMDG 4.0_*

[source,java]
----
??? new code sample
----
|=== 

==== Renaming Quorum as Split Brain Protection

Both in the API/code samples and documentation, the term "quorum" has been
replaced by "split-brain protection".

With this change, the following configuration parameters
have been renamed:

**Declarative configuration elements:**

* `quorum` -> `split-brain-protection`
* `quorum-size` -> `minimum-cluster-size`
* `quorum-ref` ->  `split-brain-protection-ref`
* `quorum-type` -> `protect-on`
* `probabilistic-quorum` -> `probabilistic-split-brain-protection`
* `recently-active-quorum` -> `recently-active-split-brain-protection`
* `quorum-function-class-name` -> `split-brain-protection-function-class-name`
* `quorum-listeners` -> `split-brain-protection-listeners`

**Programmatic configuration objects and methods:**

* `QuorumConfig` -> `SplitBrainProtectionConfig`
* `QuorumConfig.setSize()` -> `SplitBrainProtectionConfig.setMinimumClusterSize()`
* `QuorumConfig.setType()` -> `SplitBrainProtectionConfig.setProtectOn()`
* `QuorumListenerConfig` -> `SplitBrainProtectionListenerConfig`
* `QuorumEvent` -> `SplitBrainProtectionEvent`
* `QuorumService` -> `SplitBrainProtectionService`
* `QuorumService.getQuorum()` -> `SplitBrainProtectionService.getSplitBrainProtection()`
* `isPresent()` -> `hasMinimumSize()`
* `setQuorumName()` -> `setSplitBrainProtectionName()`
* `addQuorumConfig()` -> `addSplitBrainProtectionConfig()`
* `newProbabilisticQuorumConfigBuilder()` -> `newProbabilisticSplitBrainProtectionConfigBuilder()`
* `newRecentlyActiveQuorumConfigBuilder()` -> `newRecentlyActiveSplitBrainProtectionConfigBuilder()`

See the following table for a before/after sample.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,xml]
----
<hazelcast>
    ...
    <quorum name="quorumRuleWithFourMembers" enabled="true">
        <quorum-size>4</quorum-size>
    </quorum>
    <map name="default">
        <quorum-ref>quorumRuleWithFourMembers</quorum-ref>
    </map>
    ...
</hazelcast>
----

| *_After IMDG 4.0_*

[source,xml,options="nowrap"]
----
<hazelcast>
    ...
    <split-brain-protection name="splitBrainProtectionRuleWithFourMembers" enabled="true">
        <minimum-cluster-size>4</minimum-cluster-size>
    </split-brain-protection>
    <map name="default">
        <split-brain-protection-ref>splitBrainProtectionRuleWithFourMembers</split-brain-protection-ref>
    </map>
    ...
</hazelcast>
----
|===

==== Renaming getID as getClassId

The `getId()` method of the `IdentifiedDataSerializable` interface
is a method with a common name, meaning a naming conflict would happen frequently.
For example, database entities also have a `getId()` method.
Therefore, it has been renamed as `getClassId()`.

See the following table showing the interface code before and after IMDG 4.0.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java,options="nowrap"]
----
package com.hazelcast.nio.serialization;

public interface IdentifiedDataSerializable extends DataSerializable {

    int getFactoryId();

    int getId();
}
----

| *_After IMDG 4.0_*

[source,java,options="nowrap"]
----
package com.hazelcast.nio.serialization;

public interface IdentifiedDataSerializable extends DataSerializable {

    int getFactoryId();

    int getClassId();
}

----
|===

==== Renaming `group` as `cluster`

The `group` configuration element has been renamed
as `cluster`.

See the following table showing before/after samples.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java,options="nowrap"]
----
Config config = new Config();
config.getGroupConfig().setName( "production" );
----

| *_After IMDG 4.0_*

[source,java,options="nowrap"]
----
Config config = new Config();
config.getClusterName( "production" );
----
|===


==== Introducing Lambda Friendly Interfaces

===== Entry Processor

The classes `AbstractEntryProcessor` and `EntryBackupProcessor`
have been removed to make entry processor lambda friendly.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
        map.executeOnKey(key, new AbstractEntryProcessor<Integer, Employee>() {

            @Override
            public Object process(Map.Entry<Integer, Employee> entry) {
                Employee employee = entry.getValue();
                if (employee == null) {
                    employee = new Employee();
                }
                employee.setSalary(value);
                entry.setValue(employee);
                return null;
            }
        });
----

| *_After IMDG 4.0_*

[source,java]
----
        map.executeOnKey(key,
                entry -> {
                    Employee employee = entry.getValue();
                    if (employee == null) {
                        employee = new Employee();
                    }
                    employee.setSalary(value);
                    entry.setValue(employee);
                    return null;
                });
----
|===

===== Projection

The `Projection` class has been made a functional interface. It was
an abstract class before.


[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java]
----
??? old code sample
----

| *_After IMDG 4.0_*

[source,java]
----
??? new code sample
----
|===

===== Functional and Serializable Interfaces

Introduces interfaces with single abstract method which declares a
checked exception. The interfaces are also `Serializable` and can be
readily used when providing a lambda which is then serialized.

For this purpose, the `Projection` class has been converted to an interface
to make it more lambda friendly.

Also, the custom query attribute classes including the following have been
converted to functional interfaces:

* `ArgumentParser`
* `ValueCallback`
* `ValueCollector`
* `ValueExtractor`
* `ValueReader`

==== Expanding Nullable/Nonnull Annotations

The APIs of the distributed data structures have been made cleaner
by adding `Nullable` and `Nonnull` annotations, and
their API documentation have been improved:

* Now, it is obvious when looking at the API where `null` is allowed and
where it is not.
* Some methods were throwing `NullPointerException` while others were throwing
`IllegalArgumentException`. Some methods actually allowed `null` but there was
no indication that they did.
* A method when used on the member would accept `null` and have some behavior
accordingly while, on the client, the method would throw a `NullPointerException`.
Now, the behavior of the member and client have been aligned.

The data structures and interfaces enhanced in this sense are listed below:

* IQueue, ISet, IList
* IMap, MultiMap, Replicated Map
* `Cluster`
* ITopic
* Ringbuffer
* Scheduled Executor

==== Removal of ICompletableFuture

In Hazelcast IMDG 3.x series, `com.hazelcast.core.ICompletableFuture` was
introduced to enable reactive programming style. `ICompletableFuture` was
intended as a temporary, JDK 6 compatible replacement for `java.util.concurrent.CompletableFuture`
that was introduced in Java 8. Since Hazelcast 4.0 requires Java 8, the user-facing
asynchronous Hazelcast API methods now have their return type changed from
`ICompletableFuture` to Java 8's `CompletionStage`.

See the following table for the before/after samples.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

[source,java,options="nowrap"]
----
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.ICompletableFuture;
import com.hazelcast.cp.CPSubsystem;
import com.hazelcast.cp.CPSubsystemManagementService;

public class CpSubsystemAPI {

    public static void main(String[] args) throws Exception {
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

        CPSubsystem cpSubsystem = hazelcastInstance.getCPSubsystem();

        CPMember localMember = cpSubsystem.getLocalCPMember();

        {
        CPSubsystemManagementService managementService = cpSubsystem.getCPSubsystemManagementService();
        ICompletableFuture<Collection<CPGroupId>> future = managementService.getCPGroupIds();
        Collection<CPGroupId> groups = future.get();
        }
    }
}
----

| *_After IMDG 4.0_*

[source,java,options="nowrap"]
----
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.cp.CPSubsystem;
import com.hazelcast.cp.CPSubsystemManagementService;

import java.util.concurrent.CompletionStage;

public class CpSubsystemAPI {

    public static void main(String[] args) throws Exception {
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();

        CPSubsystem cpSubsystem = hazelcastInstance.getCPSubsystem();

        {
        CPSubsystemManagementService managementService = cpSubsystem.getCPSubsystemManagementService();
        CompletionStage<Collection<CPGroupId>> future = managementService.getCPGroupIds();
        Collection<CPGroupId> groups = future.toCompletableFuture().get();
        }
    }
}
----
|===



==== WAN Replication Changes

The previously known `wan-publisher` (or `WanPublisherConfig`) has been separated into
two configuration elements/classes to be used for built-in and custom WAN publishers:

* `batch-publisher` (declarative configuration) or `WanBatchReplicationPublisherConfig` (programmatic configuration)
* `custom-publisher` (declarative configuration) or `CustomWanPublisherConfig` (programmatic configuration)

With this change, the `wan-publisher` configuration element has been renamed as `batch-publisher`
and `custom-publisher`, according to your publisher preference.
See the following table for the before/after configuration examples.

[cols="1a"]
|===

| *_Before IMDG 4.0_*

The following was an example declarative configuration for `wan-publisher`:

[source,xml,options="nowrap"]
----
<wan-publisher group-name="nyc" publisher-id="nycPublisherId">
    <class-name>com.hazelcast.enterprise.wan.impl.replication.WanBatchReplication</class-name>
    <queue-capacity>15000</queue-capacity>
    <queue-full-behavior>DISCARD_AFTER_MUTATION</queue-full-behavior>
    <initial-publisher-state>REPLICATING</initial-publisher-state>
    <wan-sync>
        <consistency-check-strategy>NONE</consistency-check-strategy>
    </wan-sync>
    <properties>
        <property name="endpoints">10.3.5.1:5701,10.3.5.2:5701</property>
        <property name="batch.size">1000</property>
        <property name="batch.max.delay.millis">2000</property>
        <property name="response.timeout.millis">60000</property>
        <property name="ack.type">ACK_ON_OPERATION_COMPLETE</property>
        <property name="snapshot.enabled">false</property>
        <property name="group.password">nyc-pass</property>
    </properties>
</wan-publisher>
----

| *_After IMDG 4.0_*

And the following is the equivalent of the above configuration after IMDG 4.0:

[source,xml]
----
<batch-publisher>
            <cluster-name>nyc</cluster-name>
            <publisher-id>nycPublisherId</publisher-id>
            <batch-size>1000</batch-size>
            <batch-max-delay-millis>2000</batch-max-delay-millis>
            <response-timeout-millis>60000</response-timeout-millis>
            <acknowledge-type>ACK_ON_OPERATION_COMPLETE</acknowledge-type>
            <initial-publisher-state>REPLICATING</initial-publisher-state>
            <snapshot-enabled>false</snapshot-enabled>
            <queue-full-behavior>DISCARD_AFTER_MUTATION</queue-full-behavior>
            <queue-capacity>10000</queue-capacity>
    <target-endpoints>10.3.5.1:5701,10.3.5.2:5701</target-endpoints>
    <wan-sync>
        <consistency-check-strategy>NONE</consistency-check-strategy>
    </wan-sync>
</batch-publisher>
----
|===

Besides the above change, the following cleanups have been performed for
the WAN replication:

* Removed the unused `removeBackup`, `addMapQueue`, `addCacheQueue` methods
* Added the new family of `removeWanEvents` methods which should cover
the existing cases
* Renamed the `clearQueues` method as `removeWanEvents`
* Removed the `WanReplicationEndpoint.collectReplicationData` method
Introduced two methods for the same purpose which produce and accept any kind of
WAN event container:
** `prepareEventContainerReplicationData`
** `processEventContainerReplicationData`

==== Predicate API Cleanups

The following refactors and cleanups have been performed
on the public Predicate related API:

* Moved the following classes from the `com.hazelcast.query` package
to `com.hazelcast.query.impl.predicates`:
** `IndexAwarePredicate`
** `VisitablePredicate`
** `SqlPredicate/Parser`
** `TruePredicate`
* Moved the `FalsePredicate` and `SkipIndexPredicate` classes to
the `com.hazelcast.query.impl.predicates` package.
* Converted `PagingPredicate` and `PartitionPredicate` to interfaces
and added `PagingPredicateImpl` and `PartitionPredicateImpl` to
the `com.hazelcast.query.impl.predicate` package.
* Converted `PredicateBuilder` and `EntryObject` to interfaces (and made
`EntryObject` a nested interface in `PredicateBuilder`) and added
`PredicateBuilderImpl` to the `com.hazelcast.query.impl.predicates` package.
* The public API classes/interfaces are no longer extend `IndexAwarePredicate`/
`VisitablePredicate`; this dependency has been moved to the `impl` classes.
* Introduced the new factory methods in `Predicates`:
** `newPredicateBuilder()`
** `sql()`
** `pagingPredicate()`
** `partitionPredicate()`

Consequently, the public Predicate API now provides only interfaces (`Predicate`,
`PagingPredicate` and `PartitionPredicate`) with no dependencies on any internal APIs.

=== Upgrading to Hazelcast IMDG 3.12.x

* **REST endpoint authentication**: The authentication to REST endpoints has been changed
in Hazelcast IMDG 3.12. Hazelcast IMDG 3.11.x checks group name and password, while 3.12 checks
just the group name when security is disabled, and it uses the client login modules when the security is enabled.
* **Upgrading Cluster Version From IMDG 3.11 to 3.12**:
For the IMDG versions before 3.12, REST API could be enabled by using the
`hazelcast.rest.enabled` system property, which is deprecated now.
IMDG 3.12 and newer versions introduce the `rest-api` configuration element
along with REST endpoint groups.
Therefore, a configuration change is needed specifically when performing
a rolling member upgrade from IMDG 3.11 to 3.12.
+
So, the steps listed in the above <<rolling-upgrade-procedure>> section
should be as follows:
+
. Shutdown the 3.11 member
. Wait until all partition migrations are completed
. Update the member with 3.12 binaries
. Update the configuration (see below)
. Start the member
+
For the 4th step ("Update the configuration"), the configuration
should be updated as follows:
+
[source,xml]
----
<hazelcast>
    ...    
    <rest-api enabled="true">
        <endpoint-group name="CLUSTER_WRITE" enabled="true"/>
    </rest-api>
    ...
</hazelcast>
----
+
See the <<using-the-rest-endpoint-groups>> section for more
information.

=== Upgrading from Hazelcast IMDG 3.10.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.9.x to 3.10.x and newer.

* Starting with Hazelcast 3.10, split-brain recovery is supported for
the data structures whose in-memory format is `NATIVE`.


=== Upgrading from Hazelcast IMDG 3.9.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.9.x to 3.10.x and newer.

* The https://docs.hazelcast.org/docs/3.10/manual/html-single/#requirements-and-linuxunix-configuration[system property based configuration]
for Ping Failure Detector is deprecated. Instead, use the elements to configure it, an example of which is shown below:
+
[source,xml]
----
<hazelcast>
    <network>
    ...       
        <failure-detector>
            <icmp enabled="true">
                <timeout-milliseconds>1000</timeout-milliseconds>
                <fail-fast-on-startup>true</fail-fast-on-startup>
                <interval-milliseconds>1000</interval-milliseconds>
                <max-attempts>2</max-attempts>
                <parallel-mode>true</parallel-mode>
                <ttl>255</ttl>
            </icmp>
        </failure-detector>
    </network>
    ...
</hazelcast>
----

Until Hazelcast IMDG 3.10, the configuration has been like the following:

[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.icmp.enabled">true</property>
        <property name="hazelcast.icmp.parallel.mode">true</property>
        <property name="hazelcast.icmp.timeout">1000</property>
        <property name="hazelcast.icmp.max.attempts">3</property>
        <property name="hazelcast.icmp.interval">1000</property>
        <property name="hazelcast.icmp.ttl">0</property>
    </properties>
    ...
</hazelcast>
----

=== Upgrading to Hazelcast IMDG 3.8.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.7.x to 3.8.x and newer.

* **Introducing <wan-publisher> element**: The configuration element `<target-cluster>` has been replaced with
the element `<wan-publisher>` in WAN replication configuration.
* **WaitNotifyService** interface has been renamed as **OperationParker**.
* **Synchronizing WAN Target Cluster**: The URL for the related REST call has been changed from
`+http://member_ip:port/hazelcast/rest/wan/sync/map+` to `+http://member_ip:port/hazelcast/rest/mancenter/wan/sync/map+`.
* **`JCache usage`:** Due to a compatibility problem, `CacheConfig` serialization may not
work if your member is 3.8.x where x < 5. You need to use the 3.8.5 or higher versions where the problem is fixed.


=== Upgrading to Hazelcast IMDG 3.7.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.6.x to 3.7.x and newer.

* **Important note about Hazelcast System Properties:** Even Hazelcast has not been
recommending the usage of `GroupProperties.java` class while benefiting from system properties,
there has been a change to inform to the users who have been using this class:
the class `GroupProperties.java` has been replaced by `GroupProperty.java`.
In this new class, system properties are instances of the newly introduced `HazelcastProperty` object.
You can access the names of these properties by calling the `getName()` method of `HazelcastProperty`.
* **Removal of WanNoDelayReplication**: `WanNoDelayReplication` implementation of Hazelcast's WAN Replication has been removed.
You can still achieve this behavior by setting the batch size to `1` while configuring the WanBatchReplication.
See the <<defining-wan-replication, Defining WAN Replication section>> for more information.
* **`JCache` usage:** Changes in `JCache` implementation which broke compatibility of 3.6.x clients to 3.7, 3.7.1, 3.7.2 cluster members and
vice versa. 3.7, 3.7.1, 3.7.2 clients are also incompatible with 3.6.x cluster members.
This issue only affects Java clients which use `JCache` functionality.
+
You can use a compatibility option which can be used to ensure backwards compatibility with 3.6.x clients.
+
In order to upgrade a 3.6.x cluster and clients to 3.7.3 (or later), you need to use this
compatibility option on either the member or the client side, depending on which one is upgraded first:
+
** first upgrade your cluster members to 3.7.3, adding property `hazelcast.compatibility.3.6.client=true` to your configuration;
when started with this property, cluster members are compatible with 3.6.x and 3.7.3+ clients but not with 3.7, 3.7.1, 3.7.2 clients.
Once your cluster is upgraded, you may upgrade your applications to use client version 3.7.3+.
** upgrade your clients from 3.6.x to 3.7.3, adding property `hazelcast.compatibility.3.6.server=true` to your Hazelcast client configuration.
A 3.7.3 client started with this compatibility option is compatible with 3.6.x and 3.7.3+ cluster members but incompatible with 3.7, 3.7.1, 3.7.2 cluster members.
Once your clients are upgraded, you may then proceed to upgrade your cluster members to version 3.7.3 or later.
+
You may use any of the supported ways as described in the <<system-properties, System Properties section>> to configure
the compatibility option. When done upgrading your cluster and clients, you may remove the compatibility property from
your Hazelcast member configuration.
* The `eviction-percentage` and `min-eviction-check-millis` elements are deprecated.
They are ignored if configured, since the map eviction is based on the sampling of entries.
See the <<eviction-algorithm, Eviction Algorithm section>> for details.

=== Upgrading to Hazelcast IMDG 3.6.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.5.x to 3.6.x and newer.

* **Introducing new configuration options for WAN replication:** WAN replication related system properties, which are
configured on a per member basis, can now be configured per target cluster.
The following system properties are no longer valid.
** `hazelcast.enterprise.wanrep.batch.size`, see the <<batch-size, Batch Size section>>.
** `hazelcast.enterprise.wanrep.batchfrequency.seconds`, see the <<batch-maximum-delay, Batch Maximum Delay section>>.
** `hazelcast.enterprise.wanrep.optimeout.millis`, see the <<response-timeout, Response Timeout section>>.
** `hazelcast.enterprise.wanrep.queue.capacity`, see the <<queue-capacity, Queue Capacity section>>.
* **Removal of deprecated `getId()` method**: The method `getId()` in the interface `DistributedObject` has been removed.
Please use the `getName()` method instead.
* **Change in the Custom Serialization in the C++ Client Distribution**:
Before, the method `getTypeId()` was used to retrieve the ID of the object to be serialized.
With this release, the method `getHazelcastTypeId()` is used and you give your object as a parameter to this new method.
Also, `getTypeId()` was used in your custom serializer class; it has been renamed to `getHazelcastTypeId()`, too.
* The `LOCAL` transaction type has been deprecated. Use `ONE_PHASE` for the Hazelcast IMDG releases 3.6 and higher.

=== Upgrading to Hazelcast IMDG 3.5.x

This section provides information to be considered when upgrading from Hazelcast IMDG 3.4.x to 3.5.x and newer.

* **Introducing the `spring-aware` element:** Hazelcast used `SpringManagedContext` to scan `SpringAware` annotations by default.
This was causing some performance overhead for the users who do not use `SpringAware`.
With this release, `SpringAware` annotations are disabled by default.
By introducing the `spring-aware` element, it is possible to enable it by adding the `<hz:spring-aware />` tag to the configuration.
See the <<integration-with-spring, Spring Integration section>>.


=== Upgrading to Hazelcast IMDG 3.x

This section provides information to be considered when upgrading from Hazelcast IMDG 2.x to 3.x.

* **Removal of deprecated static methods:** The static methods of Hazelcast class reaching Hazelcast data components have been removed.
The functionality of these methods can be reached from the `HazelcastInstance` interface.
You should replace the following:
+
```
Map<Integer, String> customers = Hazelcast.getMap( "customers" );
```
+
with
+
[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
// or if you already started an instance named "instance1"
// HazelcastInstance hazelcastInstance = Hazelcast.getHazelcastInstanceByName( "instance1" );
Map<Integer, String> customers = hazelcastInstance.getMap( "customers" );
----
+
* **Renaming "instance" to "distributed object":** There were confusions about the term "instance";
it was used for both the cluster members and distributed objects (map, queue, topic, etc. instances).
Starting with this release, the term "instance" is used for Hazelcast instances.
The term "distributed object" is used for map, queue, etc. instances.
You should replace the related methods with the new renamed ones.
3.0.x clients are smart clients in that they know in which cluster member the data is located,
so you can replace your lite members with native clients.
+
[source,java]
----
public static void main( String[] args ) throws InterruptedException {
  HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
  IMap map = hazelcastInstance.getMap( "test" );
  Collection<Instance> instances = hazelcastInstance.getInstances();
  for ( Instance instance : instances ) {
    if ( instance.getInstanceType() == Instance.InstanceType.MAP ) {
      System.out.println( "There is a map with name: " + instance.getId() );
    }
  }
}
----
+
with
+
[source,java]
----
public static void main( String[] args ) throws InterruptedException {
  HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
  IMap map = hz.getMap( "test" );
  Collection<DistributedObject> objects = hazelcastInstance.getDistributedObjects();
  for ( DistributedObject distributedObject : objects ) {
    if ( distributedObject instanceof IMap ) {
      System.out.println( "There is a map with name: " + distributedObject.getName() );
    }
  }
}
----
+
* **Package structure change:** `PartitionService` has been moved to the `com.hazelcast.core` package from `com.hazelcast.partition`.
* **Listener API change:** The `removeListener` methods were taking the listener object as a parameter.
But this caused confusion since the same listener object may be used as a parameter for different listener registrations.
So we have changed the listener API. The `addListener` methods returns a unique ID and you can remove a listener by using this ID.
So you should do the following replacement if needed:
+
[source,java]
----
IMap map = hazelcastInstance.getMap( "map" );
map.addEntryListener( listener, true );
map.removeEntryListener( listener );
----
+
with
+
[source,java]
----
IMap map = hazelcastInstance.getMap( "map" );
String listenerId = map.addEntryListener( listener, true );
map.removeEntryListener( listenerId );
----
+
* **IMap changes:**
** `tryRemove(K key, long timeout, TimeUnit timeunit)` returns boolean indicating whether operation is successful.
** `tryLockAndGet(K key, long time, TimeUnit timeunit)` is removed.
** `putAndUnlock(K key, V value)` is removed.
** `lockMap(long time, TimeUnit timeunit)` and `unlockMap()` are removed.
** `getMapEntry(K key)` is renamed as `getEntryView(K key)`. The returned object's type (`MapEntry` class) is renamed as `EntryView`.
** There is no predefined names for merge policies. You just give the full class name of the merge policy implementation:
+
```
<merge-policy>com.hazelcast.map.merge.PassThroughMergePolicy</merge-policy>
```
+
Also the `MergePolicy` interface has been renamed as `MapMergePolicy` and
returning null from the implemented `merge()` method causes the existing entry to be removed.
+
* **IQueue changes:** There is no change on IQueue API but there are changes on how `IQueue` is configured:
there is no backing map configuration for queue. Settings like backup count are directly configured on the queue configuration.
See the <<queue, Queue section>>.
* **Transaction API change:** Transaction API has been changed. See the <<transactions, Transactions chapter>>.
* **ExecutorService API change:** The `MultiTask` and `DistributedTask` classes have been removed.
All the functionality is supported by the newly presented interface IExecutorService.
See the <<executor-service, Executor Service section>>.
* **LifeCycleService API:** The lifecycle has been simplified. The `pause()`, `resume()`, `restart()` methods have been removed.
* **AtomicNumber:** `AtomicNumber` class has been renamed as `IAtomicLong`.
* **ICountDownLatch:** The `await()` operation has been removed. We expect users to use `await()` method with timeout parameters.
* **ISemaphore API:** The `ISemaphore` has been substantially changed. The `attach()`, `detach()` methods have been removed.
*  Before, the default value for `max-size` eviction policy was **cluster_wide_map_size**.
Starting with this release, the default is **PER_NODE**.
After upgrading, the `max-size` should be set according to this new default, if it is not changed.
Otherwise, it is likely that `OutOfMemoryException` may be thrown.
