
[[understanding-configuration]]
== Understanding Configuration

This chapter describes the options to configure your Hazelcast applications
and explains the utilities which you can make use of while configuring.
You can configure Hazelcast using one or mix of the following options:

* Declarative way
* Programmatic way
* Using Hazelcast system properties
* Within the Spring context
* Dynamically adding configuration on a running cluster

[[configuring-declaratively]]
=== Configuring Declaratively

This is the configuration option where you use an XML or a YAML configuration
file. When you download and unzip `hazelcast-{imdg-version}
.zip`, you see the following files present in the  `/bin` folder, which are
standard configuration files:

* `hazelcast.xml`: Default declarative XML configuration file for Hazelcast.
The configuration for the distributed data structures in this XML file should
be fine for most of the Hazelcast users. If not, you can tailor this XML file according
to your needs by adding/removing/modifying properties. Also see the <<setting-up-clusters,
Setting Up Clusters chapter>> for the network related configurations.
* `hazelcast.yaml`: Default YAML configuration file identical to `hazelcast.xml` in content.
* `hazelcast-full-example.xml`: Configuration file which includes all Hazelcast configuration
elements and attributes with their descriptions. It is the "superset" of `hazelcast.xml`.
You can use `hazelcast-full-example.xml` as a reference document to learn about any element
or attribute, or you can change its name to `hazelcast.xml` and start to use it as your
Hazelcast configuration file.
* `hazelcast-full-example.yaml`: YAML configuration file identical to
`hazelcast-full-example.xml` in content.
* `hazelcast-client-full-example.xml`: Complete Hazelcast Java client example configuration
file which includes all configuration elements and attributes with their descriptions. Read
more about Java client configuration <<configuring-java-client, here>>.
* `hazelcast-client-full-example.yaml`: YAML configuration file identical to
`hazelcast-client-full-example.xml` in content.
* `hazelcast-client-failover-full-example.xml`: Complete Hazelcast client failover example
configuration file which includes all Hazelcast client failover configuration elements and
attributes with their descriptions. Read about Blue-Green Deployment and Disaster Recovery
<<blue-green-deployment-and-disaster-recovery, here>>.
* `hazelcast-client-failover-full-example.yaml`: YAML configuration file identical to
`hazelcast-client-failover-full-example.xml` in content.

A part of `hazelcast.xml` is shown as an example below.

[source,xml]
----
<hazelcast>
    ...
    <cluster-name>dev</cluster-name>
    <management-center scripting-enabled="false" />
    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <outbound-ports>
        <!--
        Allowed port range when connecting to other members.
        0 or * means the port provided by the system.
        -->
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="true">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
	    </multicast>
	    <tcp-ip enabled="false">
	        <interface>127.0.0.1</interface>
                <member-list>
                    <member>127.0.0.1</member>
                </member-list>
            </tcp-ip>
        </join>
    </network>
    <map name="default">
        <time-to-live-seconds>0</time-to-live-seconds>
    </map>
    ...
</hazelcast>
----

The identical part of the configuration extracted from `hazelcast.yaml` is shown as below.

[source,yaml]
----
hazelcast:
  ...
  cluster-name: dev
  management-center:
    scripting-enabled: false
  network:
    port:
      auto-increment: true
      port-count: 100
      port: 5701
    outbound-ports:
      # Allowed port range when connecting to other nodes.
      # 0 or * means use system provided port.
      - 0
    join:
      multicast:
        enabled: true
        multicast-group: 224.2.2.3
        multicast-port: 54327
      tcp-ip:
        enabled: false
        interface: 127.0.0.1
        member-list:
          - 127.0.0.1
  map:
    default:
      time-to-live-seconds: 0
    ...
----


[[composing-declarative-configuration]]
==== Composing Declarative Configuration

You can compose the declarative configuration of your Hazelcast member or
Hazelcast client from multiple declarative
configuration snippets. In order to compose a declarative configuration, you
can `import` different
declarative configuration files. Composing configuration files is supported both
in XML and YAML configurations with the
limitation that only configuration files written in the same language can be composed.

Let's say you want to compose the declarative configuration for Hazelcast out of two
XML configurations: `development-cluster-config.xml` and `development-network-config.xml`.
These two configurations are shown below.

`development-cluster-config.xml`:

[source,xml]
----
<hazelcast>
    <cluster-name>dev</cluster-name>
</hazelcast>
----

`development-network-config.xml`:

[source,xml]
----
<hazelcast>
    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <join>
            <multicast enabled="true">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
        </join>
    </network>
</hazelcast>
----

To get your example Hazelcast declarative configuration out of the above two,
use the `<import/>` element as shown below.

[source,xml]
----
<hazelcast>
    <import resource="development-group-config.xml"/>
    <import resource="development-network-config.xml"/>
</hazelcast>
----

The above example using the YAML configuration files looks like the following:

`development-cluster-config.yaml`:

[source,yaml]
----
hazelcast:
  cluster-name: dev
----

`development-network-config.yaml`:

[source,yaml]
----
hazelcast:
  network:
    port:
      auto-increment: true
      port-count: 100
      port: 5701
    join:
      multicast:
        enabled: true
        multicast-group: 224.2.2.3
        multicast-port: 54327
----

Composing the above two YAML configuration files needs them to be imported as shown below.

[source,yaml]
----
hazelcast:
  import:
    - development-group-config.yaml
    - development-network-config.yaml
----


This feature also applies to the declarative configuration of Hazelcast client.
See the following examples.


`client-cluster-config.xml`:

[source,xml]
----
<hazelcast-client>
    <cluster-name>dev</cluster-name>
</hazelcast-client>
----

`client-network-config.xml`:

[source,xml]
----
<hazelcast-client>
    <network>
        <cluster-members>
            <address>127.0.0.1:7000</address>
        </cluster-members>
    </network>
</hazelcast-client>
----

To get a Hazelcast client declarative configuration from the above two examples,
use the `<import/>` element as shown below.

[source,xml]
----
<hazelcast-client>
    <import resource="client-cluster-config.xml"/>
    <import resource="client-network-config.xml"/>
</hazelcast-client>
----

The same client configuration using the YAML language is shown below.


`client-cluster-config.yaml`:

[source,yaml]
----
hazelcast-client:
  cluster-name: dev
----

`client-network-config.yaml`:

[source,yaml]
----
hazelcast-client:
  network:
    cluster-members:
      - 127.0.0.1:7000
----

Composing a Hazelcast client declarative configuration by importing the above two examples is shown below.

[source,yaml]
----
hazelcast-client:
  import:
    - client-cluster-config.yaml
    - client-network-config.yaml
----


NOTE: Use `<import/>` element on top level of the XML hierarchy.

NOTE: Use the `import` mapping on top level of the YAML hierarchy.

Resources from the classpath and file system may also be used to compose a declarative configuration:

[source,xml]
----
<hazelcast>
    <import resource="file:///etc/hazelcast/development-cluster-config.xml"/> <!-- loaded from filesystem -->
    <import resource="classpath:development-network-config.xml"/>  <!-- loaded from classpath -->
</hazelcast>
----

[source,yaml]
----
hazelcast:
  import:
    # loaded from filesystem
    - file:///etc/hazelcast/development-cluster-config.yaml
    # loaded from classpath
    - classpath:development-network-config.yaml
----

Importing resources with variables in their names is also supported. See the following example snippets:

[source,xml]
----
<hazelcast>
    <import resource="${environment}-cluster-config.xml"/>
    <import resource="${environment}-network-config.xml"/>
</hazelcast>
----

[source,yaml]
----
hazelcast:
  import:
    - ${environment}-cluster-config.yaml
    - ${environment}-network-config.yaml
----

NOTE: See the <<using-variables, Using Variables section>> to learn how you can set
the configuration elements with variables.

[[configuring-declaratively-yaml]]
==== Configuring Declaratively with YAML

You can configure the Hazelcast members and Java clients declaratively with YAML configuration files in
installations of Hazelcast running on Java runtime version 8 or above.

The structure of the YAML configuration follows the structure of the XML configuration.
Therefore, you can rewrite the existing XML
configurations in YAML easily. There are some differences between the XML and YAML languages
that make the two declarative configurations to slightly derive as the the following examples show.

In the YAML declarative configuration, mappings are used in which the name of the mapping node
needs to be unique within its enclosing mapping. See the following example with
configuring two maps in the same configuration file.

In the XML configuration files, we have two `<map>` elements as shown below.

[source,xml]
----
<hazelcast>
    ...
    <map name="map1">
        <!-- map1 configuration -->
    </map>
    <map name="map2">
        <!-- map2 configuration -->
    </map>
    ...
</hazelcast>
----

In the YAML configuration, the map can be configured under a mapping `map` as shown in
the following example.

[source,yaml]
----
hazelcast:
    ...
    map:
        map1:
          # map1 configuration
        map2:
          # map2 configuration
    ...
----

The XML and YAML configurations above define the same maps `map1` and `map2`.
Please note that in the YAML configuration file
there is no `name` node, instead, the name of the map is used as the name of the
mapping for configuring the given map.

There are other configuration entries that have no unique names and are listed in the
same enclosing entry. Examples to this
kind of configurations are listing the member addresses, interfaces in the networking
configurations and defining listeners. The
following example configures listeners to illustrate this.

[source,xml]
----
<hazelcast>
    ...
    <listeners>
        <listener>com.hazelcast.examples.MembershipListener</listener>
        <listener>com.hazelcast.examples.MigrationListener</listener>
        <listener>com.hazelcast.examples.PartitionLostListener</listener>
    </listeners>
    ...
</hazelcast>
----

In the YAML configuration, the listeners are defined as a sequence.

[source,yaml]
----
hazelcast:
  ...
  listeners:
    - com.hazelcast.examples.MembershipListener
    - com.hazelcast.examples.MigrationListener
    - com.hazelcast.examples.PartitionLostListener
  ...
----

Another notable difference between XML and YAML is the lack of the attributes in the
case of YAML. Everything that can be
configured with an attribute in the XML configuration is a scalar node in the YAML
configuration with the same name. See the
following example.

[source,xml]
----
hazelcast:
<hazelcast>
    ...
    <network>
        <join>
            <multicast enabled="true">
                <multicast-group>1.2.3.4</multicast-group>
                <!-- other multicast configuration options -->
            </multicast>
        </join>
    </network>
    ...
</hazelcast>
----

In the identical YAML configuration, the `enabled` attribute of the XML
configuration is a scalar node on the same level with
the other items of the multicast configuration.

[source,yaml]
----
hazelcast:
  ...
  network:
    join:
      multicast:
        enabled: true
        multicast-group: 1.2.3.4
        # other multicast configuration options
  ...
----

You can refer to the full example YAML configuration files placed in the `/bin` folder
of the downloadable `hazelcast-{imdg-version}.zip` after unzipping it. Please see the
complete list of the full example YAML configurations <<configuring-declaratively, here>>.

[[configuring-programmatically]]
=== Configuring Programmatically

Besides declarative configuration, you can configure your cluster programmatically.
For this you can create a `Config` object, set/change its properties and attributes
and use this `Config` object to create a new Hazelcast member. Following is an example
code which configures some network and Hazelcast Map properties.

[source,java]
----
include::{javasource}/ProgrammaticConfSample.java[tag=pcs]
----

To create a Hazelcast member with the above example configuration, pass the
configuration object as shown below:

```
HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance( config );
```

NOTE: The `Config` must not be modified after the Hazelcast instance is started.
In other words, all configuration must be completed before creating the `HazelcastInstance`.
Certain additional configuration elements can be added at runtime as described in the
<<dynamically-adding-data-structure-configuration-on-a-cluster, Dynamically Adding Data Structure Configuration on a Cluster section>>.

You can also create a named Hazelcast member. In this case, you should set `instanceName`
of `Config` object as shown below:

[source,java]
----
Config config = new Config();
config.setInstanceName( "my-instance" );
Hazelcast.newHazelcastInstance( config );
----

To retrieve an existing Hazelcast member by its name, use the following:

```
Hazelcast.getHazelcastInstanceByName( "my-instance" );
```

To retrieve all existing Hazelcast members, use the following:

```
Hazelcast.getAllHazelcastInstances();
```

NOTE: Hazelcast performs schema validation through the file `hazelcast-config-{imdg-version}.xsd`
which comes with your Hazelcast libraries. Hazelcast throws a meaningful exception if there
is an error in the declarative or programmatic configuration.

If you want to specify your own configuration file to create `Config`, Hazelcast supports
several ways including filesystem,
classpath, InputStream and URL.

Building `Config` from the XML declarative configuration:

* `Config cfg = new XmlConfigBuilder(xmlFileName).build();`
* `Config cfg = new XmlConfigBuilder(inputStream).build();`
* `Config cfg = new ClasspathXmlConfig(xmlFileName);`
* `Config cfg = new FileSystemXmlConfig(configFilename);`
* `Config cfg = new UrlXmlConfig(url);`
* `Config cfg = new InMemoryXmlConfig(xml);`

Building `Config` from the YAML declarative configuration:

* `Config cfg = new YamlConfigBuilder(yamlFileName).build();`
* `Config cfg = new YamlConfigBuilder(inputStream).build();`
* `Config cfg = new ClasspathYamlConfig(yamlFileName);`
* `Config cfg = new FileSystemYamlConfig(configFilename);`
* `Config cfg = new UrlYamlConfig(url);`
* `Config cfg = new InMemoryYamlConfig(yaml);`

[[configuring-with-system-properties]]
=== Configuring with System Properties

You can use system properties to configure some aspects of Hazelcast. You set
these properties as name and value pairs through declarative configuration,
programmatic configuration or JVM system property. Following are examples for
each option.

**Declarative Configuration:**

[source,xml]
----
<hazelcast>
    ...
    <properties>
        <property name="hazelcast.property.foo">value</property>
    </properties>
    ...
</hazelcast>
----

[source,yaml]
----
hazelcast:
    ...
    properties:
      hazelcast.property.foo: value
    ...
----

**Programmatic Configuration:**

[source,java]
----
Config config = new Config() ;
config.setProperty( "hazelcast.property.foo", "value" );
----

**Using JVM's `System` class or `-D` argument:**

`System.setProperty( "hazelcast.property.foo", "value" );`

or

`java -Dhazelcast.property.foo=value`

You will see Hazelcast system properties mentioned throughout this Reference Manual
as required in some of the chapters and sections. All Hazelcast system properties
are listed in the <<system-properties, System Properties appendix>> with their
descriptions, default values and property types as a reference for you.

[[configuring-within-spring-context]]
=== Configuring within Spring Context

If you use Hazelcast with link:https://spring.io/[Spring^] you can declare beans
using the namespace `hazelcast`. When you add the namespace declaration to
the element `beans` in the Spring context file, you can start to use the
namespace shortcut `hz` to be used as a bean declaration. Following is an
example Hazelcast configuration when integrated with Spring:

[source,xml]
----
<hz:hazelcast id="instance">
    <hz:config>
        <hz:cluster name="dev"/>
        <hz:network port="5701" port-auto-increment="false">
            <hz:join>
                <hz:multicast enabled="false"/>
                <hz:tcp-ip enabled="true">
                    <hz:members>10.10.1.2, 10.10.1.3</hz:members>
                </hz:tcp-ip>
            </hz:join>
        </hz:network>
    </hz:config>
</hz:hazelcast>
----

See the <<integration-with-spring, Integration with Spring section>> for
more information on Hazelcast-Spring integration.

[[dynamically-adding-data-structure-configuration-on-a-cluster]]
=== Dynamically Adding Data Structure Configuration on a Cluster

As described above, Hazelcast can be configured in a declarative or
programmatic way; configuration must be completed before starting a
Hazelcast member and this configuration cannot be altered at runtime,
thus we refer to this as _static_ configuration.

It is possible to dynamically add configuration for certain data structures at
runtime; these can be added by invoking one of the `Config.add*Config` methods on
the `Config` object obtained from a running member's `HazelcastInstance.getConfig()` method.
For example:

[source,java]
----
include::{javasource}/DynamicConfiguration.java[tag=dynconf]
----

Dynamic configuration elements must be fully configured before the invocation
of `add*Config` method: at that point, the configuration object is delivered
to every member of the cluster and added to each member's dynamic configuration,
so mutating the configuration object after the `add*Config` invocation does not have
an effect.

As dynamically added data structure configuration is propagated across all cluster
members, failures may occur due to conditions such as timeout and network partition.
The configuration propagation mechanism internally retries adding the configuration
whenever a membership change is detected. However if an exception is thrown from
`add*Config` method, the configuration may have been partially propagated to some
cluster members and adding the configuration should be retried by the user.

Adding a new dynamic configuration is supported for all `add*Config` methods except the following:

* `JobTracker`: It has been deprecated since Hazelcast 3.8.
* `SplitBrainProtectionConfig`: A new split-brain protection configuration cannot be dynamically added but other
configuration can reference split-brain protections configured in the existing static configuration.
* `WanReplicationConfig`: A new WAN replication configuration cannot be dynamically
added, however existing static ones can be referenced from other configurations,
e.g., a new dynamic `MapConfig` may include a `WanReplicationRef` to a statically
configured WAN replication.
* `ListenerConfig`: Listeners can be instead added at runtime via other API such as
`HazelcastInstance.getCluster().addMembershipListener` and
`HazelcastInstance.getPartitionService().addMigrationListener`.

Keep in mind that this feature also works for Hazelcast Java clients.
See the following example:

[source,java]
----
HazelcastInstance client = HazelcastClient.newHazelcastClient();
MapConfig mCfg = new MapConfig("test");
mCfg.setTimeToLiveSeconds(15);
client.getConfig().addMapConfig(mCfg);
HazelcastClient.shutdownAll();
----

NOTE: If your cluster has data structures with configurations added during runtime,
those configurations are lost when a cluster restart occurs due to any reason since
they are not persisted. This will be improved in the future Hazelcast IMDG releases.

[[handling-configuration-conflicts]]
==== Handling Configuration Conflicts

Attempting to add a dynamic configuration, when a static configuration for
the same element already exists, throws `InvalidConfigurationException`. For example,
assuming we start a member with the following fragment in `hazelcast.xml` configuration:

[source,xml]
----
<hazelcast>
    ...
    <map name="sessions">
        ...
    </map>
    ...
</hazelcast>
----

Then adding a dynamic configuration for a map with the name `sessions` throws
a `InvalidConfigurationException`:

[source,java]
----
HazelcastInstance instance = Hazelcast.newHazelcastInstance();

MapConfig sessionsMapConfig = new MapConfig("sessions");

// this will throw ConfigurationException:
instance.getConfig().addMapConfig(sessionsMapConfig);
----

When attempting to add dynamic configuration for an element for which dynamic
configuration has already been added, then if a configuration conflict is detected
a `InvalidConfigurationException` is thrown. For example:

[source,java]
----
HazelcastInstance instance = Hazelcast.newHazelcastInstance();

MapConfig sessionsMapConfig = new MapConfig("sessions").setBackupCount(0);
instance.getConfig().addMapConfig(sessionsMapConfig);

MapConfig sessionsWithBackup = new MapConfig("sessions").setBackupCount(1);
// throws ConfigurationException because the new MapConfig conflicts with existing one
instance.getConfig().addMapConfig(sessionsWithBackup);

MapConfig sessionsWithoutBackup = new MapConfig("sessions").setBackupCount(0);
// does not throw exception: new dynamic config is equal to existing dynamic config of same name
instance.getConfig().addMapConfig(sessionsWithoutBackup);
----

==== Dynamic Data Structure Configuration and User Customizations

Dynamically added data structure configuration may reference
user customizations, such as a user-provided `MapLoader` implementation referenced
by a `MapConfig`. User customizations can be usually configured using either of the following:

* by specifying a class or factory class name, e.g., `MapStoreConfig.setClassName`, and letting the
Hazelcast members instantiate the object
* by providing an existing instance, e.g., `MapStoreConfig.setImplementation`.

When dynamically adding new a data structure configuration with user customizations,
take the following considerations into account:

* For the user customizations submitted as a class name or factory class name, the referenced
classes are resolved  lazily. Therefore, they should be either already on each member's local
classpath or resolvable via <<member-user-code-deployment-beta, user code deployment>>.
* When the user customizations are submitted as instances (or similarly factory instances),
the instances themselves have to be serializable. This is because the entire configuration needs
to be sent over the network to all cluster members, and their classes have to be available
on each member's local classpath.

[[checking-configuration]]
=== Checking Configuration

When you start a Hazelcast member without passing a `Config` object, as explained
in the <<configuring-programmatically, Configuring Programmatically section>>,
Hazelcast checks the member's configuration as follows:

* First, it looks for the `hazelcast.config` system property. If it is set, its
value is used as the path. This is useful if you want to be able to change your
Hazelcast configuration; you can do this because it is not embedded within the
application. You can set the `config` option with the following command:
+
```
-Dhazelcast.config=`*`<path to the hazelcast.xml or hazelcast.yaml>
```
+
[NOTE]
====
The suffix of the filename is used to determine the language of the configuration.
If the suffix is `.xml` the
configuration file is parsed as an
XML configuration file. If it is `.yaml`, the configuration file is parsed as a
YAML configuration file.
====
+
The path can be a regular one or a classpath reference with the prefix `classpath:`.
* If the above system property is not set, Hazelcast then checks whether there is
a `hazelcast.xml` file in the working directory.
* If not, it then checks whether `hazelcast.xml` exists on the classpath.
* If not, it then checks whether `hazelcast.yaml` exists in the working directory.
* If not, it then checks whether `hazelcast.yaml` exists on the classpath.
* If none of the above works, Hazelcast loads the default configuration
(`hazelcast.xml`) that comes with your Hazelcast package.

Before configuring Hazelcast, please try to work with the default configuration
to see if it works for you. This default configuration should be fine for most of
the users. If not, you can consider to modify the configuration to be more suitable
for your environment.

[[configuration-pattern-matcher]]
=== Configuration Pattern Matcher

You can give a custom strategy to match an item name to a configuration pattern. By
default Hazelcast uses a simplified wildcard matching. See <<using-wildcards, Using Wildcards section>>
for this.
A custom configuration pattern matcher can be given by using either member or client `config`
objects, as shown below:

[source,java]
----
// Setting a custom config pattern matcher via member config object
Config config = new Config();
config.setConfigPatternMatcher(new ExampleConfigPatternMatcher());
----

And the following is an example pattern matcher:

[source,java]
----
include::{javasource}/ExampleConfigPatternMatcher.java[tag=patternmatcher]
----


[[using-wildcards]]
=== Using Wildcards

Hazelcast supports wildcard configuration for all distributed data structures that
can be configured using `Config`, that is, for all except `IAtomicLong`,
`IAtomicReference`. Using an asterisk (*) character in the name, different
instances of maps, queues, topics, semaphores, etc. can be configured by a
single configuration.

A single asterisk (*) can be placed anywhere inside the configuration name.

For instance, a map named `com.hazelcast.test.mymap` can be configured using
one of the following configurations:

[source,xml]
----
<hazelcast>
    ...
    <map name="com.hazelcast.test.*">
        ...
    </map>

    <!-- OR -->

    <map name="com.hazel*">
        ...
    </map>

    <!-- OR -->

    <map name="*.test.mymap">
        ...
    </map>

    <!-- OR -->

    <map name="com.*test.mymap">
        ...
    </map>
    ...
</hazelcast>
----

A queue named `com.hazelcast.test.myqueue` can be configured using one
of the following configurations:

[source,xml]
----
<hazelcast>
    ...
    <queue name="*hazelcast.test.myqueue">
        ...
    </queue>

    <!-- OR -->

    <queue name="com.hazelcast.*.myqueue">
        ...
    </queue>
    ...
</hazelcast>
----

[NOTE]
====

* You can use only a single asterisk as a wildcard for each data
structure configuration.
* If you have matching wildcard configurations for a data structure,
the most specific (longest) one is used when configuring it. Let's say
you have a map named `mymap.customer.name` and you have map configurations
`mymap.\*` and `mymap.customer.*`. Hazelcast uses `mymap.customer.*` to
configure this map.
+
As another example, assume that you have a map named `mymap.customer.name`, and
map configurations `mymap.\*.name` and `mymap.customer.*`. Hazelcast uses `mymap.customer.*`
to configure this map. As you see, the longest character length before the asterisk makes
it the most specific, so it wins the configuration.
====

[[using-variables]]
=== Using Variables

In your Hazelcast and/or Hazelcast Client declarative configuration, you can use
variables to set the values of the elements. This is valid when you set a system
property programmatically or you use the command line interface. You can use a variable
in the declarative configuration to access the values of the system properties you set.

For example, see the following command that sets two system properties.

```
-Dcluster.name=dev
```

Let's get the values of these system properties in the declarative
configuration of Hazelcast, as shown below.

In the XML configuration:

[source,xml]
----
<hazelcast>
    <cluster-name>${cluster.name}</cluster-name>
</hazelcast>
----

In the YAML configuration:

[source,yaml]
----
hazelcast:
  cluster-name: ${cluster.name}
----

This also applies to the declarative configuration of Hazelcast Java Client,
as shown below.

[source,xml]
----
<hazelcast-client>
    <cluster-name>${cluster.name}</cluster-name>
</hazelcast-client>
----

[source,yaml]
----
hazelcast-client:
  cluster-name: ${cluster.name}
----

If you do not want to rely on the system properties, you can use the
`XmlConfigBuilder` or `YamlConfigBuilder` and explicitly
set a `Properties` instance, as shown below.

[source,java]
----
Properties properties = new Properties();

// fill the properties, e.g., from database/LDAP, etc.

XmlConfigBuilder builder = new XmlConfigBuilder();
builder.setProperties(properties);
Config config = builder.build();
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
----


[[variable-replacers]]
=== Variable Replacers

Variable replacers are used to replace custom strings during loading the configuration,
e.g., they can be used to mask sensitive information such as usernames and passwords.
Of course their usage is not limited to security related information.

Variable replacers implement the interface `com.hazelcast.config.replacer.spi.ConfigReplacer`
and they are configured only
declaratively: in the Hazelcast's declarative configuration files, i.e.,
`hazelcast.xml`, `hazelcast.yaml` and `hazelcast-client
.xml`, `hazelcast-client.yaml`. See the ``ConfigReplacer``s
link:{docBaseUrl}/javadoc/com/hazelcast/config/replacer/spi/ConfigReplacer.html[Javadoc^]
for basic information on how a replacer works.

Variable replacers are configured within the element `<config-replacers>` under `<hazelcast>`,
as shown below.

In the XML configuration:

[source,xml]
----
<hazelcast>
    ...
    <config-replacers fail-if-value-missing="false">
        <replacer class-name="com.acme.MyReplacer">
            <properties>
                <property name="propName">value</property>
                ...
            </properties>
        </replacer>
        <replacer class-name="example.AnotherReplacer"/>
    </config-replacers>
    ...
</hazelcast>
----

In the YAML configuration:

[source,yaml]
----
hazelcast:
    ...
    config-replacers:
      fail-if-value-missing: false
      replacers:
        - class-name: com.acme.MyReplacer
          properties:
            propName: value
            ...
        - class-name: example.AnotherReplacer
    ...
----

As you can see, `<config-replacers>` is the parent element for your replacers,
which are declared using the `<replacer>` sub-elements. You can define multiple
replacers under the `<config-replacers>.` Here are the descriptions of elements
and attributes used for the replacer configuration:

* `fail-if-value-missing`: Specifies whether the loading configuration process
stops when a replacement value is missing. It is an optional attribute and its default value is true.
* `class-name`: Full class name of the replacer.
* `<properties>`: Contains names and values of the properties used to configure a replacer.
Each property is defined using the `<property>` sub-element. All of the properties are
explained in the upcoming sections.

The following replacer classes are provided by Hazelcast as example implementations of
the `ConfigReplacer` interface. Note that you can also implement your own replacers.

* `EncryptionReplacer`
* `PropertyReplacer`

NOTE: There is also a `ExecReplacer` which runs an external command and uses its
standard output as the value for the variable. See its
link:https://github.com/hazelcast/hazelcast-code-samples/blob/master/variable-replacers/src/main/java/com/hazelcast/sample/replacer/ExecReplacer.java[code sample^].

Each example replacer is explained in the below sections.

==== EncryptionReplacer

This example `EncryptionReplacer` replaces encrypted variables by its plain
form. The secret key for encryption/decryption is generated from a password
which can be a value in a file and/or environment specific values, such as MAC
address and actual user data.

Its full class name is `com.hazelcast.config.replacer.EncryptionReplacer` and
the replacer prefix is `ENC`. The following are the properties used to
configure this example replacer:

* `cipherAlgorithm`: Cipher algorithm used for the encryption/decryption.
Its default value is AES.
* `keyLengthBits`: Length of the secret key to be generated in bits. Its default value is 128 bits.
* `passwordFile`: Path to a file whose content should be used as a part
of the encryption password. When the property is not provided no file is
used as a part of the password. Its default value is null.
* `passwordNetworkInterface`: Name of network interface whose MAC address
should be used as a part of the encryption password. When the property is
not provided no network interface property is used as a part of the password.
Its default value is null.
* `passwordUserProperties`: Specifies whether the current user properties
(`user.name` and `user.home`) should be used as a part of the encryption
password. Its default value is true.
* `saltLengthBytes`: Length of a random password salt in bytes. Its default
value is 8 bytes.
* `secretKeyAlgorithm`:  Name of the secret-key algorithm to be associated
with the generated secret key. Its default value is AES.
* `secretKeyFactoryAlgorithm`: Algorithm used to generate a secret key from
a password. Its default value is PBKDF2WithHmacSHA256.
* `securityProvider`: Name of a Java Security Provider to be used for retrieving
the configured secret key factory and the cipher. Its default value is null.

NOTE: Older Java versions may not support all the algorithms used as defaults.
Please use the property values supported your Java version.


As a usage example, let's create a password file and generate the encrypted
string out of this file as instructed below:

. Create the password file: `echo '/Za-uG3dDfpd,5.-' > /opt/master-password`
. Define the encrypted variables:
+
```
java -cp hazelcast-*.jar \
    -DpasswordFile=/opt/master-password \
    -DpasswordUserProperties=false \
    com.hazelcast.config.replacer.EncryptionReplacer \
    "aCluster"
$ENC{Gw45stIlan0=:531:yVN9/xQpJ/Ww3EYkAPvHdA==}
```
+
. Configure the replacer and put the encrypted variables into the configuration:
+
[source,xml]
----
<hazelcast>
    <config-replacers>
        <replacer class-name="com.hazelcast.config.replacer.EncryptionReplacer">
            <properties>
                <property name="passwordFile">/opt/master-password</property>
                <property name="passwordUserProperties">false</property>
            </properties>
        </replacer>
    </config-replacers>
    <cluster-name>$ENC{Gw45stIlan0=:531:yVN9/xQpJ/Ww3EYkAPvHdA==}</cluster-name>
</hazelcast>
----
+
. Check if the decryption works:
+
```
java -jar hazelcast-*.jar
Apr 06, 2018 10:15:43 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Apr 06, 2018 10:15:44 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [aCluster] [3.10-SNAPSHOT] Prefer IPv4 stack is true.
```

As you can see in the logs, the correctly decrypted cluster name value
("aCluster") is used.

==== PropertyReplacer

The `PropertyReplacer` replaces variables by properties with the given
name. Usually the system properties are used, e.g., `${user.name}`.
There is no need to define it in the declarative configuration files.

Its full class name is `com.hazelcast.config.replacer.PropertyReplacer`
and the replacer prefix is empty string ("").


==== Implementing Custom Replacers

You can also provide your own replacer implementations. All replacers
have to implement the interface `com.hazelcast.config.replacer.spi.ConfigReplacer`.
A simple snippet is shown below.

[source,java]
----
public interface ConfigReplacer {
    void init(Properties properties);
    String getPrefix();
    String getReplacement(String maskedValue);
}
----
