[[wanbatchreplication-implementation]]
==== WAN Batch Publisher Implementation

Hazelcast IMDG Enterprise Edition offers the WAN batch publisher implementation for WAN replication.

As you see in the above configuration examples, this implementation is specified simply by using
the `batch-publisher` element (in the declarative configuration) or the `WanBatchPublisherConfig`
class (in the programmatic configuration) when defining a WAN replication publisher.

The WAN batch publisher transmits WAN events (map and cache updates) between clusters in batches. It waits until:

* a pre-defined number of replication events are generated, (see the <<batch-size, Batch Size section>>)
* or a pre-defined amount of time is passed (see the <<batch-maximum-delay, Batch Maximum Delay section>>).

==== Configuring WAN Replication for IMap and ICache

You can configure WAN replication for Hazelcast's IMap and ICache data structures.
To enable WAN replication for an IMap or ICache instance, you can use the `wan-replication-ref` element.
Each IMap and ICache instance can have a different WAN replication configuration.

**Enabling WAN Replication for IMap:**

Imagine you have different distributed maps, however only one of those maps should be replicated to a target cluster.
To achieve this, configure the map that you want to be replicated by adding the `wan-replication-ref` element in
the map configuration as shown below.

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        ...
    </wan-replication>
    <map name="my-shared-map">
        <wan-replication-ref name="london-wan-rep">
            <merge-policy>com.hazelcast.spi.merge.PassThroughMergePolicy</merge-policy>
            <republishing-enabled>false</republishing-enabled>
        </wan-replication-ref>
    </map>
    ...
</hazelcast>
----

The following is the equivalent program matic configuration:

[source,java]
----
include::{javasource}/wan/EnablingWRforMap.java[tag=wrmap]
----

You see that we have `my-shared-map` configured to replicate itself to the cluster targets defined in the earlier
`wan-replication` element.

`wan-replication-ref` has the following elements;

* `name`: Name of `wan-replication` configuration. IMap or ICache instance uses this `wan-replication` configuration.
* `merge-policy`: Resolve conflicts that occur when the target cluster already has the replicated entry key.
This configuration element is optional. If it is not specified, `com.hazelcast.spi.merge.PassThroughMergePolicy`
will be used as the merge policy.
* `republishing-enabled`: When enabled, an incoming event to a member is forwarded to target cluster of that member.
Enabling the event republishing is useful in a scenario where cluster A replicates to cluster B and
cluster B replicates to cluster C. You do not need to enable republishing when all your clusters
replicate to each other.

When using Active-Active Replication, multiple clusters can simultaneously update the same
entry in a distributed data structure. You can configure a merge policy to resolve these potential
conflicts, as shown in the above example configuration (using the `merge-policy` sub-element under
the `wan-replication-ref` element).

Hazelcast provides the following merge policies for IMap:

* `com.hazelcast.spi.merge.PutIfAbsentMergePolicy`: Incoming entry merges from the source map to
the target map if it does not exist in the target map.
* `com.hazelcast.spi.merge.HigherHitsMergePolicy`: Incoming entry merges from the source map to
the target map if the source entry has more hits than the target one.
* `com.hazelcast.spi.merge.PassThroughMergePolicy`: Incoming entry merges from the source map to
the target map unless the incoming entry is not null.
* `com.hazelcast.spi.merge.ExpirationTimeMergePolicy`: Incoming entry merges from the source map to
the target map if the source entry will expire later than the destination entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.
* `com.hazelcast.spi.merge.LatestAccessMergePolicy`: Incoming entry merges from the source map to
the target map if the source entry has been accessed more recently than the destination entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.
* `com.hazelcast.spi.merge.LatestUpdateMergePolicy`: Incoming entry merges from the source map to
the target map if the source entry has been updated more recently than the target entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.

NOTE: When using WAN replication, please note that only key based events are replicated to the target cluster.
Operations like `clear`, `destroy`, `evict` and `evictAll` are NOT replicated.

**Enabling WAN Replication for ICache:**

The following is a declarative configuration example for enabling WAN Replication for ICache:

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        ...
    </wan-replication>
    <cache name="my-shared-cache">
        <wan-replication-ref name="london-wan-rep">
            <merge-policy>com.hazelcast.spi.merge.PassThroughMergePolicy</merge-policy>
            <republishing-enabled>true</republishing-enabled>
        </wan-replication-ref>
    </cache>
    ...
</hazelcast>
----

The following is the equivalent programmatic configuration:

[source,java]
----
include::{javasource}/wan/EnablingWRforCache.java[tag=wrcache]
----

NOTE: Caches that are created dynamically do not support WAN replication functionality.
Cache configurations should be defined either declaratively (by XML) or programmatically on both
source and target clusters.

Hazelcast provides the following merge policies for ICache:

* `com.hazelcast.spi.merge.PutIfAbsentMergePolicy`: Incoming entry merges from the source cache to
the target cache if it does not exist in the target cache.
* `com.hazelcast.spi.merge.HigherHitsMergePolicy`: Incoming entry merges from the source cache to
the target cache if the source entry has more hits than the target one.
* `com.hazelcast.spi.merge.PassThroughMergePolicy`: Incoming entry merges from the source cache to
the target cache unless the incoming entry is not null.
* `com.hazelcast.spi.merge.ExpirationTimeMergePolicy`: Incoming entry merges from the source cache to
the target cache if the source entry will expire later than the destination entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.
* `com.hazelcast.spi.merge.LatestAccessMergePolicy`: Incoming entry merges from the source cache to
the target cache if the source entry has been accessed more recently than the destination entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.
* `com.hazelcast.spi.merge.LatestUpdateMergePolicy`: Incoming entry merges from the source cache to
the target cache if the source entry has been updated more recently than the target entry.
Please note that this merge policy can only be used when the clusters' clocks are in sync.