=== Defining WAN Replication

WAN Replication is defined and configured using the `wan-replication` configuration
element as can be seen in the above examples.

You have the following implementation-wise options to define a WAN Replication:

* using the built-in WAN Replication implementation provided by Hazelcast (WAN batch publisher)
* using your own implementation (WAN custom publisher)

And, you have the following endpoint-wise options:

* using static endpoints (when you want to provide the IP addresses of target IMDG members)
* using Discovery SPI (when you want to target IMDG members on various cloud infrastructures)
+
You can use at most one of these endpoint specifications when defining a single WAN publisher.

Let's describe each implementation- and endpoint-wise options in the following sections.

[[wanbatchreplication-implementation]]
==== Using the Built-In WAN Batch Publisher 

Hazelcast IMDG offers the built-in WAN batch publisher implementation for WAN replication.

As you see in the above configuration examples, this implementation is specified simply by using
the `batch-publisher` element (in the declarative configuration) or the `WanBatchPublisherConfig`
class (in the programmatic configuration) when defining a WAN replication publisher.

The WAN batch publisher transmits WAN events (map and cache updates) between clusters in batches. It waits until:

* a pre-defined number of replication events are generated, (see the <<batch-size, Batch Size section>>)
* or a pre-defined amount of time is passed (see the <<batch-maximum-delay, Batch Maximum Delay section>>).

Here is a declarative example on using and configuring `batch-publisher`:

[source,xml,options="nowrap"]
----
<hazelcast>
    <wan-replication name="london-wan-rep">
        <batch-publisher>
            <cluster-name>london</cluster-name>
            ...
        </batch-publisher>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
    </cache>
</hazelcast>
----

Above, you notice that we have configured the instance to replicate a map and a cache to a target cluster
with the cluster name `london`. WAN Replication will check that this cluster name matches during connection
establishment to each endpoint. This does not serve as a security measure though. This serves only to prevent
misconfiguration where the source cluster would mistakenly replicate to the wrong cluster and as an attempt to
detect and prevent loops where the same WAN event would be infinitely forwarded between the same clusters.

The `wan-replication` configuration element defines a single WAN replication scheme. Hazelcast maps and caches
are configured to replicate to a single WAN replication scheme and different maps and different caches can be
configured to replicate to different WAN replication schemes. Simply put, a WAN replication scheme may be viewed
as several target clusters and different Hazelcast structures can replicate to different target clusters
simultaneously. As such, a single WAN replication scheme can contain multiple WAN replication publishers.
It has the following essential sub-elements and attributes:

* `name`: Name of your WAN replication scheme. This name is referenced in IMap or ICache configuration when you want
to enable WAN Replication for these data structures (using the element `wan-replication-ref` in the configuration
of IMap or ICache).
* `batch-publisher`: Enables use of a WAN publisher which uses the built-in WAN replication implementation in the
Hazelcast Enterprise Edition. See the <<wanbatchreplication-implementation, WAN Batch Publisher Implementation>> section
for more information. It defines how to connect to the target cluster and how WAN events are sent to a specific target
endpoint. As mentioned above, just before the configuration example, the target endpoints can be a different cluster
defined by static IPs or discovered using a cloud discovery mechanism.

As mentioned previously, `batch-publisher` element is used to configure the built-in WAN replication implementation.
It has the following sub-elements:

* `cluster-name`: Sets the cluster name used as an endpoint cluster name for authentication
on the target endpoint. If there is no separate publisher ID element defined, this cluster name
is also used as a WAN publisher ID. This ID is then used for identifying the publisher in a
WAN replication scheme. It is mandatory to set this attribute.
* `publisher-id`: Sets the publisher ID used to identify the publisher in a WAN replication scheme.
Setting this ID may be useful when the `wan-replication` element contains multiple WAN publishers and the
cluster names are not unique for all of the WAN replication publishers in a single WAN replication scheme.
It is optional to set this attribute. If this ID is not specified, the `cluster-name` is used as a publisher ID.
* `target-endpoints`: IP addresses and ports of the cluster members for which the WAN replication is implemented.
It is enough to specify some of the member IP/ports available in the target cluster, i.e., you don’t need to
provide the IP/ports of all members in there. WAN does not perform the discovery of other members in the target cluster;
it only expects that the IP addresses you provide are available.
* `sync`: Configuration for the WAN sync mechanism.
* `aws`: Configuration for discovery strategy for Amazon EC2 discovery plugin.
* `gcp`: Configuration for discovery strategy for Google cloud platform discovery plugin.
* `azure`: Configuration for discovery strategy for Microsoft Azure discovery plugin.
* `kubernetes`: Configuration for discovery strategy for Kubernetes discovery plugin.
* `eureka`: Configuration for discovery strategy for Eureka discovery plugin.
* `discovery-strategies`: Set its `enabled` attribute to true for discovery in various cloud infrastructures.
You can define multiple discovery strategies using the `discovery-strategy` sub-element and its elements.

Using this configuration, the cluster replicates to a cluster with the name `london`.
The `london` cluster should have a similar configuration if you want to run in Active-Active mode.

You can achieve various WAN topologies using different configurations on different clusters. For instance,
if the New York and London cluster configurations contain the `wan-replication` element and the Tokyo cluster
does not, it might mean that the New York and London clusters are active endpoints and Tokyo is a passive endpoint.

[[defining-custom-wr]]
==== Using the WAN Custom Publisher

In addition to using the Hazelcast provided WAN Replication implementation, you can implement your own
replication mechanism using the WAN publisher SPI.

Following is the configuration snippet where `replicatedMap` and `replicatedCache` use the custom implementation
`com.my.WanPublisher` to replicate map and cache updates.

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        <custom-publisher>
            <publisher-id>myCustomPublisher</publisher-id>
            <class-name>com.my.WanPublisher</class-name>
            <properties>
                <property name="prop1">val1</property>
                <property name="prop2">val2</property>
            </properties>
        </custom-publisher>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </cache>
    ...
</hazelcast>
----

The `custom-publisher` is used to configure a custom implementation of a WAN replication implementing
`com.hazelcast.wan.WanPublisher`. For example, you might implement replication to Kafka or some JMS queue or even
write out map and cache event changes to a log on disk. It has the following sub-elements:

* `class-name`: Mandatory configuration value defining the fully qualified class name of the
WAN publisher implementation. The class must implement `com.hazelcast.wan.WanPublisher`.
* `publisher-id`: Mandatory configuration value for the publisher ID used for identifying the
publisher in a `WanReplicationConfig`. This ID will be used to refer to this specific WAN publisher in
a certain WAN replication scheme.

In some cases, specifying the configuration on the source/active cluster is enough to fully implement your use case.
This is the case when you don't have any target/passive Hazelcast cluster which consumes these events. In cases when
you do have a target Hazelcast cluster and you wish to use a custom WAN Replication implementation, you will need to
configure the target cluster as well. For example, you might want to implement WAN Replication by transmitting WAN events
through some JMS queue like ActiveMQ. In this case, you need to implement both your custom WAN publisher and WAN consumer.

Below is a configuration example for specifying a custom WAN replication consumer on the target/passive cluster:

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        <consumer>
            <class-name>com.my.WanConsumer</class-name>
            <properties>
                <property name="prop1">val1</property>
                <property name="prop2">val2</property>
            </properties>
        </consumer>
    </wan-replication>
</hazelcast>
----

The `consumer` is used to configure the implementation of the `com.hazelcast.wan.WanConsumer` interface
which will be used to retrieve and process WAN events. A custom WAN consumer allows you to
define custom processing logic and is used in combination with a custom WAN publisher.

The `consumer` configuration element has the following sub-elements:

* `class-name`: Name of the class implementing a custom WAN consumer (`com.hazelcast.wan.WanConsumer`).
* `properties`: Properties for the custom WAN consumer. These properties are accessible when initializing the WAN consumer.
You can define the host, username and password for the host, name of the queue to be polled by the consumer, etc.

[[wanbatchreplication-static-endpoints]]
==== Using the Static Endpoints

This is most suitable when the endpoints have static IP addresses which will not change for
the duration of the lifecycle of the source cluster. You will then list these addresses in the WAN publisher
configuration and WAN Replication will try to keep a stable connection to each of those.

Below is an example of declarative configuration of WAN Replication between two Hazelcast clusters. Here, we show the
configuration that is needed on the source ("active") cluster. In most cases, the target ("passive") cluster does not
need any kind of configuration and configuring the source cluster is enough for WAN Replication to function normally.

Here, we show the simplest working XML configuration to replicate to a target cluster with the cluster-name `london`.

[source,xml,options="nowrap"]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        <batch-publisher>
            <cluster-name>london</cluster-name>
            <target-endpoints>10.3.5.1:5701, 10.3.5.2:5701</target-endpoints>
        </batch-publisher>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </cache>
    ...
</hazelcast>
----

We can see that we have configured the map named `replicatedMap` and cache named `replicatedCache` to
replicate to the cluster named `london` on two endpoints - `10.3.5.1:5701, 10.3.5.2:5701`. The `london` cluster
might have more members than these two but only these two will receive WAN events and forward them to other
members in the `london` cluster or to other clusters if WAN event forwarding is enabled.
Please notice that the WAN Replication configuration is referenced in map and cache configuration by name, here
`london-wan-rep`.

And the following is the equivalent programmatic configuration snippet:

[source,java]
----
include::{javasource}/wan/ExampleWANReplicationConfiguration.java[tag=wrc]
----

The default settings for WAN Replication will suit most use cases. If, however, you have specific needs or if you
would like to fine-tune the behavior of WAN Replication for your application, please refer to the
<<tuning-wr, Tuning WAN Replication>> section for more information.

[[wanbatchreplication-discovery-spi]]
==== Using the Discovery SPI

In addition to defining target cluster endpoints with static IP addresses,
you can configure WAN to work with the discovery SPI and determine the endpoint IP addresses at runtime.
It may be suitable when you don't know the list of static IP addresses of the target cluster at
startup time or in cases when the list of available target endpoints is subject to change during the lifecycle of the
source cluster.

In relation to the above, using the Discovery SPI allows you to use WAN with endpoints on various cloud
infrastructures (such as Amazon EC2 or GCP Compute) where
the IP address is not known in advance. Typically you use a readily available discovery SPI plugin such as
link:https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS EC2 discovery plugin^],
link:https://github.com/hazelcast/hazelcast-gcp[Hazelcast GCP discovery plugin^], or similar.
You can store the list of IP addresses in those infrastructures and use these plugins
to read from that list.

For more advanced cases, you can provide your own discovery SPI implementation with custom logic for
determining the WAN target endpoints such as looking up the endpoints in some service registry or even
reading the endpoint addresses from a file.

NOTE: When using the discovery SPI, WAN always connects to the public address of the members returned by
the discovery SPI implementation. This is opposite to the cluster membership mechanism using
the discovery SPI where a member connects to a different member in the same cluster through its private address.
Should you prefer for WAN to use the private address of the discovered member as well,
please use the `use-endpoint-private-address` publisher element (see below).

Following is an example of setting up the WAN replication with the EC2 discovery plugin.
You must have the link:https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS EC2 discovery plugin^] on the classpath.

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        <batch-publisher>
            <cluster-name>london</cluster-name>
            <discovery-strategies>
                <discovery-strategy enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                    <properties>
                        <property name="access-key">test-access-key</property>
                        <property name="secret-key">test-secret-key</property>
                        <property name="region">test-region</property>
                        <property name="iam-role">test-iam-role</property>
                        <property name="host-header">ec2.test-host-header</property>
                        <property name="security-group-name">test-security-group-name</property>
                        <property name="tag-key">test-tag-key</property>
                        <property name="tag-value">test-tag-value</property>
                        <property name="connection-timeout-seconds">10</property>
                        <property name="hz-port">5701</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </batch-publisher>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </cache>
    ...
</hazelcast>
----

The `hz-port` property defines the port or the port range on which the target endpoint is running.
The default port range 5701-5708 is used if this property is not defined.
This is needed because the Amazon API which the AWS plugin uses does not provide
the port on which Hazelcast is running, only the IP address. For some other discovery SPI implementations,
this might not be necessary and it might discover the port as well, e.g., by looking up in a service registry.

The other properties are the same as when using the `aws` element. In case of EC2 discovery you can configure
the WAN replication using the `aws` element. You may use either of these, but not both at the same time.

[source,xml]
----
<hazelcast>
    ...
    <wan-replication name="london-wan-rep">
        <batch-publisher>
            <cluster-name>london</cluster-name>
            <use-endpoint-private-address>false</use-endpoint-private-address>
            <aws enabled="true">
                <access-key>my-access-key</access-key>
                <secret-key>my-secret-key</secret-key>
                <region>us-west-1</region>
                <security-group-name>hazelcast-sg</security-group-name>
                <tag-key>type</tag-key>
                <tag-value>hz-members</tag-value>
                <hz-port>5701</hz-port>
            </aws>
        </batch-publisher>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </cache>
    ...
</hazelcast>
----

See the <<aws-element, aws element>> and the <<configuring-client-for-aws, Configuring Client for AWS>>
sections for the descriptions of above AWS configuration elements.

You can also define the WAN publisher with Discovery SPI using the programmatic configuration:

[source,java]
----
include::{javasource}/wan/ExampleWANReplicationDiscoveryConfiguration.java[tag=wrdc]
----

The default settings for WAN Replication will suit most use cases. If, however, you have specific needs or if you
would like to fine-tune the behavior of WAN Replication for your application, please refer to the
<<tuning-wr, Tuning WAN Replication>> section for more information.

==== Customizing WAN Event Processing on Passive/Target Cluster

In addition to customizing behavior of the source cluster and how WAN events are sent and retained, you can also
configure some aspects of how WAN events are processed on the receiving (target/passive) cluster. In addition, you
can also define a custom implementation of a WAN event consumer. A custom WAN consumer allows you to define custom
processing logic and is usually used in combination with a custom WAN publisher. A custom consumer is optional and
you may simply omit defining it which causes the default processing logic to be used. See the
<<defining-custom-wr, Using the WAN Custom Publisher section>> for more information.

Below you can see an example configuration of the target/passive cluster where we configure how incoming WAN events
are processed.

[source,xml,options="nowrap"]
----
<hazelcast>
    ...

    <wan-replication name="london-wan-rep">
        <consumer>
            <persist-wan-replicated-data>false</persist-wan-replicated-data>
        </consumer>
    </wan-replication>

    <map name="replicatedMap">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </map>

    <cache name="replicatedCache">
        <wan-replication-ref name="london-wan-rep"/>
        ...
    </cache>
    ...
</hazelcast>
----

In the configuration above you can see that the WAN Replication configuration is again matched by WAN replication
scheme name to the exact map and cache configuration. This means that different structures can process WAN events
differently.

The processing behavior is configured using the `consumer` element. It has the following sub-elements:

* `persist-wan-replicated-data`: When set to `true`, an incoming event over WAN replication can be
persisted to a database for example, otherwise it is not persisted. Default value is `true`.
