[[wan-replication-failure-detection-and-recovery]]
=== Failure Detection and Recovery

The failure detection and recovery mechanisms in WAN handle failures during WAN replication and
they closely interact with the list of endpoints that WAN is replicating to.
There might be some small differences when using static endpoints or the Discovery SPI but
here we will outline the general mechanism of failure detection and recovery.

==== WAN Target Endpoint List

The WAN connection manager maintains a list of public addresses that it can replicate to at any moment.
This list may change over time as failures are detected or as new addresses are discovered when using the Discovery SPI.
The connection manager does not eagerly create connections to these addresses as
they are added to the list to avoid overloading the endpoint with connections from all members using
the same configuration. It tries to connect to the endpoint just before WAN events are about to be transmitted.
This means that if there are no updates on the map or cache using WAN replication, there are no
WAN events and the connection will not be established to the endpoint.

When more than one endpoint is configured, traffic is load balanced between them using
the partition, so that the same partitions are always sent to the same target member, ensuring ordering by partition.

==== WAN Failure Detection

If using the Hazelcast IMDG Enterprise edition class `WanBatchReplication`
(see the <<defining-wan-replication, Defining WAN replication section>>), the WAN replication catches
any exceptions when sending the WAN events to the endpoint. In the case of an exception,
the endpoint is removed from the endpoint list to which WAN replicates and the WAN events are resent to
a different address. The replication is retried until it is successful.

==== WAN Endpoint Recovery

The WAN connection manager tries to "rediscover" new endpoints periodically.
The period is 10 seconds by default but can be configured using the `discovery-period-seconds` element
(see the <<defining-wan-replication, Defining WAN replication section>>).

The discovered endpoints depend on the configuration used to define WAN replication.
If using static WAN endpoints (by using the `target-endpoints` element), the discovered endpoints are always the same and
are equal to the values defined in the configuration.
If using Discovery SPI with WAN, the discovered endpoints may be different each time.

When the discovery returns a list of endpoints (addresses), the WAN target endpoint list is updated.
Newly discovered endpoints are added and endpoints which are no longer in the discovered list are removed.
Newly discovered endpoints may include addresses to which WAN replication has previously failed.
This means that once a new WAN event is about to be sent, a connection is reestablished to
the previously failed endpoint and WAN replication is retried. The endpoint can later
be again removed from the target endpoint list if the replication again encounters failure.

==== Backing Up Event Queues

WAN replication backs up its event queues to other members to prevent event loss
in case of member failures.

WAN replication's backup mechanism depends on the related data structures' backup operations.
Note that, WAN replication is supported for IMap and ICache.
That means, as far as you set a backup count for your IMap or ICache instances,
WAN replication events generated by these instances are also replicated.